### ISSUE TITLE
pay_for.py doesn't work

### ISSUE THREAD

**Issue by f3x** [habanoz/tezos-reward-distributor#118]
____ ______ ______
|_   _|| ___ \|  _  \
  | |  | |_/ /| | | |
  | |  |    / | | | |
  | |  | |\ \ | |/ /
  \_/  \_| \_||___/

--------------------------------------------
Copyright Huseyin ABANOZ 2019
huseyinabanox@gmail.com
Please leave copyright information
--------------------------------------------
2019-10-23 07:58:38,906 - MainThread - Tezos Reward Distributor - Pay For Script is Starting
2019-10-23 07:58:38,906 - MainThread - --------------------------------------------
2019-10-23 07:58:38,906 - MainThread - DRY RUN MODE
2019-10-23 07:58:38,906 - MainThread - --------------------------------------------
2019-10-23 07:58:38,906 - MainThread - Arguments Configuration = {
 "network": "MAINNET",
 "reward_data_provider": "prpc",
 "reports_base": "~/pymnt/reports",
 "config_dir": "~/pymnt/cfg",
 "node_addr": "127.0.0.1:8732",
 "dry_run": true,
 "dry_run_no_consumers": false,
 "executable_dirs": "~/,~/tezos",
 "docker": false,
 "verbose": false,
 "paymentaddress": "alias",
 "payments_file": "./pay.txt"
}
2019-10-23 07:58:38,906 - MainThread - Loading master configuration file /home/tezos/pymnt/cfg/master.yaml
Traceback (most recent call last):
  File "./src/pay_for.py", line 210, in <module>
    main(args)
  File "./src/pay_for.py", line 106, in main
    reports_dir = os.path.expanduser(args.reports_dir)
AttributeError: 'Namespace' object has no attribute 'reports_dir'

How to reproduce:
$ python3 ./src/pay_for.py -D alias ./pay.txt

OS: Ubuntu 16, Python 3.7.5

**Comment by jdsika** [comment]
I am closing this because the intended use is to use main as entry point.
