### ISSUE TITLE
error running on OSX (DUNE Network)

### ISSUE THREAD

**Issue by Z1Quest** [habanoz/tezos-reward-distributor#126]
Running Version 5.13
getting the following error when running on MAC OSX - Please note no errors if running for specific cycle... 

Traceback (most recent call last):
  File "src/main.py", line 259, in <module>
    main(args)
  File "src/main.py", line 142, in main
    recent = get_latest_report_file(payments_root)
  File "src/main.py", line 196, in get_latest_report_file
    key=lambda x: int(x))
  File "src/main.py", line 196, in <lambda>
    key=lambda x: int(x))
ValueError: invalid literal for int() with base 10

**Comment by jdsika** [comment]
Please look at the dedicated project for [Dune](https://github.com/habanoz/dune-reward-distributor/)
