### ISSUE TITLE
How to configure email

### ISSUE THREAD

**Issue by Xa52c** [habanoz/tezos-reward-distributor#136]
how do you configure email.ini on ubuntu? do you have to install anything? i tried using my gmail credentials and got this error:

`
2019-11-19 10:39:14,584 - consumer0 - Error at reward payment
Traceback (most recent call last):
  File "/home/xxxx/tezos-reward-distributor/src/pay/payment_consumer.py", line 128, in run
    self.mm.send_payment_mail(pymnt_cycle, report_file, nb_failed, nb_injected)
  File "/home/xxxx/tezos-reward-distributor/src/emails/email_manager.py", line 60, in send_payment_mail
    self.default["recipients"], [payments_file])
  File "/home/xxxx/tezos-reward-distributor/src/emails/email_worker.py", line 40, in send
    smtp.login(self.user, self.password)
  File "/usr/lib/python3.7/smtplib.py", line 697, in login
    "SMTP AUTH extension not supported by server.")
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.`

**Comment by jdsika** [comment]
I think this was solved by introducing SSL in PR #138 - please test again and reopen when you have issues
