### ISSUE TITLE
TRD Finishes Without Resetting the Virtual TTY Mode

### ISSUE THREAD

**Issue by gaia** [habanoz/tezos-reward-distributor#143]
**Describe the bug**

I thought I was getting the error because I was running TRD in a container, and entering the container with `lxc exec <container-name> -- sudo /bin/bash` (`not a tty`).  So I installed TRD into a non container environment (`/dev/pts/0`), and the problem persisted.

A `reset` is required, after CTRL-C, to get to see what you type in the terminal again. This might be related to the fact that TRD does not exit, even when I use `python3 src/main.py -C 173 -M 3 -P rpc`

Could this be because the pymt acct address (via signer, encrypted) has never transacted?

More details on what is happening (non TRD specific) at https://askubuntu.com/a/172747/111533

**Expected behavior**
Stopping successfully and releasing control back to the terminal

**Screenshots**

```
2019-12-14 13:47:52,664 - MainThread - --------------------------------------------------------
2019-12-14 13:47:52,664 - MainThread - Sensitive operations are in progress!
2019-12-14 13:47:52,664 - MainThread - Please wait while the application is being shut down!
2019-12-14 13:47:52,664 - MainThread - --------------------------------------------------------
2019-12-14 13:47:52,665 - MainThread - Lock file removed!
---- waited for 10 minutes or more, then pressed  CTRL-C----
Exception ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Environment**
 - Source Code Build
 - Chain mainnet
 - `python3 src/main.py -C 173 -M 3 -P rpc` or `python3 src/main.py -C 173 -M 3 -P prpc`

**Comment by gaia** [comment]
Solved. The problem was likely pip dependency hell. Installed again on a clean ubuntu install and it exits fine.
