### ISSUE TITLE
Signer Signs Request But "Unknown client response format"

### ISSUE THREAD

**Issue by gaia** [habanoz/tezos-reward-distributor#150]
**Describe the bug**

`python3 src/main.py -C 174 -M 3 -P rpc`:

```
2019-12-15 17:46:36,323 - producer  - Run mode ONETIME satisfied. Terminating ...
2019-12-15 17:46:36,324 - producer  - Producer returning ...
2019-12-15 17:46:41,969 - MainThread - Interrupted.
2019-12-15 17:46:41,969 - MainThread - --------------------------------------------------------
2019-12-15 17:46:41,969 - MainThread - Sensitive operations are in progress!
2019-12-15 17:46:41,970 - MainThread - Please wait while the application is being shut down!
2019-12-15 17:46:41,970 - MainThread - --------------------------------------------------------
2019-12-15 17:46:41,970 - MainThread - Lock file removed!
2019-12-15 17:47:10,752 - consumer0 - batch payment attempt 2/3 for current batch failed with error
Traceback (most recent call last):
  File "/home/tezos/scripts/tezos-reward-distributor/src/pay/batch_payer.py", line 184, in pay_single_batch
    status, operation_hash = self.attempt_single_batch(payment_items, op_counter, verbose, dry_run=dry_run)
  File "/home/tezos/scripts/tezos-reward-distributor/src/pay/batch_payer.py", line 352, in attempt_single_batch
    operation_hash = parse_json_response(inject_command_response)
  File "/home/tezos/scripts/tezos-reward-distributor/src/util/rpc_utils.py", line 34, in parse_json_response
    raise Exception("Unknown client response format")
Exception: Unknown client response format
2019-12-15 17:47:51,475 - consumer0 - batch payment attempt 3/3 for current batch failed with error
Traceback (most recent call last):
  File "/home/tezos/scripts/tezos-reward-distributor/src/pay/batch_payer.py", line 184, in pay_single_batch
    status, operation_hash = self.attempt_single_batch(payment_items, op_counter, verbose, dry_run=dry_run)
  File "/home/tezos/scripts/tezos-reward-distributor/src/pay/batch_payer.py", line 352, in attempt_single_batch
    operation_hash = parse_json_response(inject_command_response)
  File "/home/tezos/scripts/tezos-reward-distributor/src/util/rpc_utils.py", line 34, in parse_json_response
    raise Exception("Unknown client response format")
Exception: Unknown client response format
2019-12-15 17:47:51,475 - consumer0 - Payment of batch 1 is complete, in 3 attempt(s)
2019-12-15 17:47:51,476 - consumer0 - Processing completed for 80 payment items, 80 failed.
```

signer shows several instances (1 per attempt)

```
Dec 15 17:47:49 - client.signer: Request for signing 4629 bytes of data for key tz1_____, magic byte = 03
Dec 15 17:47:49 - client.signer: Signing data for key payments
```

signer is launched with

`tezos-signer launch socket signer -a 127.0.0.1 -p 22000 -W -M 0x03`

**Expected behavior**

Successful payout,

**Environment**
 - Source Code Build (current)
 - Mainnet (current)
 - `python3 src/main.py -C 174 -M 3 -P rpc`
 - Python 3.6.9
 - Fresh Ubuntu 18.04.3 and TRD install

**Comment by amzid** [comment]
The response of the client after injecting the operation could not parsed correctly: `operation_hash = parse_json_response(inject_command_response)`.
Can you run the script using -V (for verbose logs) and provide the response of the client which results in this error? This can be found under logs/app.log.

**Comment by gaia** [comment]
Ah that's where -V goes. Here:

`consumer0 - <-- Verbose : Answer is |Command failed : Error while applying operation ooFtw7_________op: branch refused (Error: Unrevealed manager key for contract tz1___________.)`

**Comment by amzid** [comment]
I unfortunately did not get any message on keybase. 
But, are you sure that the pkh of the manager key was revealed? Did you do any transactions or payouts from this payout address before?

**Comment by gaia** [comment]
Nope, first time using this address on TS. The address shows up on tzstats because it has been sent funds. I also just revealed it, for the first time, and now it works.

Thank you for your help! The address needs to be revealed. Sorry if I missed that in the instructions!
