### ISSUE TITLE
Retry Payment Fails: 'Namespace' object has no attribute 'reports_dir

### ISSUE THREAD

**Issue by gaia** [habanoz/tezos-reward-distributor#151]
**Describe the bug**

`python3 src/retry_failed.py`

```
Traceback (most recent call last):
  File "src/retry_failed.py", line 200, in <module>
    main(args)
  File "src/retry_failed.py", line 120, in main
    reports_dir = os.path.expanduser(args.reports_dir)
AttributeError: 'Namespace' object has no attribute 'reports_dir'
```

```
$ ll /home/tezos/pymnt/reports/tz1QLXqnfN51dkjeghXvKHkJfhvGiM5gK4tc/payments/failed/174.csv
-rw-rw-r-- 1 tezos tezos 4409 Dec 15 17:47 /home/tezos/pymnt/reports/tz1QLXqnfN51dkjeghXvKHkJfhvGiM5gK4tc/payments/failed/174.csv
```

**Expected behavior**
Failed payments retried

**Environment**
 - Source Code Build (current)
 - Mainnet (current)
 - `python3 src/main.py -C 174 -M 3 -P rpc`
 - Python 3.6.9
 - Fresh Ubuntu 18.04.3 and TRD install

**Comment by gaia** [comment]
On hold for the next time a retry is attempted, possibly because address had not been revealed (see #150 ) .
