### ISSUE TITLE
TRD does not shutdown gracefully

### ISSUE THREAD

**Issue by denver-s** [habanoz/tezos-reward-distributor#153]
**Describe the bug**
Running with `-M 3` or force stop with `Ctrl+C` does not shut down TRD gracefully and you need to close the bash terminal.

**To Reproduce**
1. Run `python3 src/main -C 170 -M 3`
2. Wait until it produces a report

**Expected behavior**
It should shutdown.

**Debug log**

TRD did not shutdown, so after a while I tried to terminate with `Ctrl+C` but it produced another error. I had to close the terminal window after that.

```
2019-12-16 19:59:20,376 - producer  - Run mode ONETIME satisfied. Terminating ...
2019-12-16 19:59:20,377 - producer  - Producer returning ...
2019-12-16 19:59:24,040 - MainThread - Interrupted.
2019-12-16 19:59:24,041 - MainThread - --------------------------------------------------------
2019-12-16 19:59:24,041 - MainThread - Sensitive operations are in progress!
2019-12-16 19:59:24,042 - MainThread - Please wait while the application is being shut down!
2019-12-16 19:59:24,042 - MainThread - --------------------------------------------------------
Exception ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by amzid** [comment]
Were the reports generated?

**Comment by denver-s** [comment]
Yes.

**Comment by amzid** [comment]
It seems like the producer does not return properly. I unfortunately could not reproduce it. Do you still get this issue?

**Comment by utdrmac** [comment]
@denver-s Is this still an issue for you? Typically when I press ctrl-c, it takes up to 60s for everything to stop gracefully. The internal threads are on sleep-wait-check loops, so you have to wait for their sleep to finish before they check 'do i need to exit?'

**Comment by denver-s** [comment]
I am afraid to tell that when running `-M 2` it just doesn't terminate, and after pressing ctrl+c it "end" but my bash terminal is not usable anymore.

**Comment by denver-s** [comment]
In addition, my command is the following:
`python3 src/main.py --dry_run --run_mode 2 --initial_cycle 222 --release_override -11 --reward_data_provider tzstats`

CSVs are created correctly. It just doesn't end afterwards.

**Comment by utdrmac** [comment]
@denver-s What OS/shell/python3 are you using? I'm unable to reproduce this as well using Ubuntu 16.04 and CentOS 7, both using bash4 and python3.6.8

**Comment by denver-s** [comment]
Ubuntu 18.04.4 LTS, Python 3.6.9, Bash 4.4.20

**Comment by denver-s** [comment]
I figured out the issue: the payout address did not have an unencrypted secret key, so probably tezos-client was waiting for a password to be typed in.
