### ISSUE TITLE
connection 

### ISSUE THREAD

**Issue by goodpen** [habanoz/tezos-reward-distributor#162]
Traceback (most recent call last):
  File "/home/ubuntu/tezos-reward-distributor/src/pay/payment_producer.py", line 225, in try_to_pay
    reward_model = self.reward_api.get_rewards_for_cycle_map(pymnt_cycle)
  File "/home/ubuntu/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 45, in get_rewards_for_cycle_map
    current_level, current_cycle = self.__get_current_level()
  File "/home/ubuntu/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 123, in __get_current_level
    head = self.do_rpc_request(self.COMM_HEAD.format(self.node_url))
  File "/home/ubuntu/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 113, in do_rpc_request
    resp = requests.get(request, timeout=time_out)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mainnet.tezrpc.me', port=443): Max retries exceeded with url: /chains/main/blocks/head (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdc683d0da0>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))

**Comment by daboooooo** [comment]
I got the same error message. Did you fix it?

**Comment by goodpen** [comment]
Yes, use —help search -P prpc data providers and choose tzstats

**Comment by daboooooo** [comment]
> Yes, use —help search -P prpc data providers and choose tzstats

got it. thanks!
