### ISSUE TITLE
Disable founders_map,owners_map,supporters_set,specials_map

### ISSUE THREAD

**Issue by atomlab** [habanoz/tezos-reward-distributor#17]
I want sent reward only them who delegate to me. How can I disable sent rewards to founders_map,owners_map,supporters_set,specials_map addresses?

**Comment by habanoz** [comment]
supporters_set is used to determine no fee delegators. If you want to receive baking fee from everyone, live it empty.

Specials_map is used to determine customers with non standard baking fee. If everybody pays the same baking fee leave this empty.

Founders_map can be left empty. No payment will go to founders. Instead their share of rewards will remain in baking account and increase staking balance. Same holds true for owners_map.

**Comment by habanoz** [comment]
Closing this issue. You may open again if you need to.

**Comment by atomlab** [comment]
Short question. What format variables founders_map,owners_map,supporters_set,specials_map addresses if I want not used them?

In this place calculated values. that means values should be exists and non zero? 

https://github.com/habanoz/tezos-reward-distributor/blob/genericsig/src/main.py
```
# all shares in the map must sum up to 1
def validate_map_share_sum(share_map, map_name):
    if abs(1 - sum(share_map.values()) > 1e-4):  # a zero check actually
        raise Exception("Map '{}' shares does not sum up to 1!".format(map_name))
```
I can't set zero values 
`founders_map={"":0.0}`

```
  File "src/main.py", line 438, in <module>                                                                                                                                                                 
    main(args)                                                                                                                                                                                              
  File "src/main.py", line 321, in main                                                                                                                                                                     
    validate_map_share_sum(founders_map, "founders map")                                                                                                                                                    
  File "src/main.py", line 290, in validate_map_share_sum                                                                                                                                                   
    raise Exception("Map '{}' shares does not sum up to 1!".format(map_name))                                                                                                                               
Exception: Map 'founders map' shares does not sum up to 1! 
```
or  remove it
`founders_map={""}`
because script fail by exception:
```
  File "src/main.py", line 321, in main
    validate_map_share_sum(founders_map, "founders map")
  File "src/main.py", line 289, in validate_map_share_sum
    if abs(1 - sum(share_map.values()) > 1e-4):  # a zero check actually
AttributeError: 'set' object has no attribute 'values'
```
if like that

`founders_map={"":0.1}`

empty address gets into forge opteration

```
{"kind":"transaction","source":"tz1NfEiS2uJsX43vowNjau5pdqg3Nvy8whvc","destination":"","fee":"1274","counter":"86619","gas_limit": "10100", "storage_limit": "0","amount":"598725"}
```

**Comment by habanoz** [comment]
Just use {}. For example :
`founders_map={}`

Empty address should not be allowed. I add this to roadmap. Openning the issue until it is done.

**Comment by atomlab** [comment]
_src/BusinessConfiguration.py_

```
# baker's bussiness parameters

# baker's 'tz' address, NOT A KT address
BAKING_ADDRESS = "tz1NfEiS2uJsX43vowNjau5pdqg3Nvy8whvc"

# standard fee that is valid for everybody
STANDARD_FEE=0.045
# founders that shares the profits. map of founder payment address and share of the profit. Shares should sum up to 1.
founders_map={}
# deposit owners map of address and deposit ratio which must sum up to 1
owners_map={}
# no fee customers, e.g. founders, supporters
supporters_set={}
# customers with special rates. map of KT address and baking fee
specials_map={}
```

```
python3 src/main.py tezos_zero1 --executable_dirs /opt/tezos-zeronet/bin/ --node_addr 127.0.0.1:8742 -N ZERONET -C 698 -M 3 -V
...
2018-12-18 20:02:21,896 - main - INFO - MainThread - huseyinabanox@gmail.com
2018-12-18 20:02:21,896 - main - INFO - MainThread - Please leave copyright information
2018-12-18 20:02:21,896 - main - INFO - MainThread - --------------------------------------------
2018-12-18 20:02:21,896 - main - DEBUG - MainThread - Client command is /opt/tezos-zeronet/bin/tezos-client
Traceback (most recent call last):
  File "src/main.py", line 438, in <module>
    main(args)
  File "src/main.py", line 321, in main
    validate_map_share_sum(founders_map, "founders map")
  File "src/main.py", line 290, in validate_map_share_sum
    raise Exception("Map '{}' shares does not sum up to 1!".format(map_name))
Exception: Map 'founders map' shares does not sum up to 1!
```

**Comment by habanoz** [comment]
Right. I am mistaken. Some changes are necessary.

**Comment by habanoz** [comment]
I see your point. An update is necessary. However no sooner than 1 week. I can merge pull requests if anyone can Provide.
