### ISSUE TITLE
api.tezos.org.ua cloudflare failure

### ISSUE THREAD

**Issue by utdrmac** [habanoz/tezos-reward-distributor#189]
Just tried to pay C188 and there's some CloudFlare failure/blocker. Even though fetching /head failed, the code continued to attempt to calculate payments, each request failing.

Need better error handling here. If fetching /head fails, everything else afterwards should not happen at all and code should just sleep and treat as a temp issue to try again later.

```
Traceback (most recent call last):
  File "/home/bb/tezos-reward-distributor/src/pay/payment_producer.py", line 225, in try_to_pay
    reward_model = self.reward_api.get_rewards_for_cycle_map(pymnt_cycle)
  File "/home/bb/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 34, in get_rewards_for_cycle_map
    current_level, current_cycle = self.__get_current_level()
  File "/home/bb/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 113, in __get_current_level
    head = self.do_rpc_request(COMM_HEAD.format(self.node_url))
  File "/home/bb/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 105, in do_rpc_request
    raise Exception("Request '{} failed with status code {}, after {}, unique request_id {}".format(request, resp.status_code, time_out, resp.headers['CF-RAY']))
Exception: Request 'https://api.tezos.org.ua/chains/main/blocks/head failed with status code 524, after 120, unique request_id 55a566eacd11efe9-EWR
```

**Comment by utdrmac** [comment]
Switched to `-P prpc -Ap https://rpc.tulip.tools/mainnet/` and all worked without issue.

**Comment by sergattic** [comment]
Related [Issue](https://github.com/habanoz/tezos-reward-distributor/issues/194) with explanation and suggestion was created
