### ISSUE TITLE
tezos-signer not signing anything.

### ISSUE THREAD

**Issue by logart89** [habanoz/tezos-reward-distributor#190]
Hello

Journal is telling me that it detected 10 rewards for cycle 188 (using the TRD service)
```
journalctl --follow --unit=tezos-reward.service
-- Logs begin at Fri 2019-10-18 18:26:03 CDT. --
Jan 24 18:04:06 logart2 python3[9263]:     raise Exception("Attribute {} not found in application configuration.".format(attr))
Jan 24 18:04:06 logart2 python3[9263]: Exception: Attribute reactivate_zeroed not found in application configuration.
Jan 24 18:04:06 logart2 python3[9263]: 2020-01-24 18:04:06,127 - producer  - Checking for pending payments : checking 188 <= 194 - (5 + 1) - 0
Jan 24 18:04:06 logart2 python3[9263]: 2020-01-24 18:04:06,128 - producer  - Payment cycle is 188
Jan 24 18:04:39 logart2 python3[9263]: 2020-01-24 18:04:39,365 - producer  - Total rewards before processing is 472,604,224 mutez.
Jan 24 18:04:39 logart2 python3[9263]: 2020-01-24 18:04:39,366 - producer  - Total rewards after  processing is 472,604,224 mutez.
Jan 24 18:04:44 logart2 python3[9263]: 2020-01-24 18:04:44,373 - producer  - Calculation report is created at '/home/logart/pymnt/reports/tz1WctSwL49BZtdWAQ75NY6vr4xsAx6oKdah/calculations/188.csv'
Jan 24 18:04:44 logart2 python3[9263]: 2020-01-24 18:04:44,373 - producer  - Reward creation is done for cycle 188, created 10 rewards.
Jan 24 18:04:59 logart2 python3[9263]: 2020-01-24 18:04:59,404 - producer  - Checking for pending payments : checking 189 <= 194 - (5 + 1) - 0
Jan 24 18:04:59 logart2 python3[9263]: 2020-01-24 18:04:59,404 - producer  - No pending payments for cycle 189, current cycle is 194
```

But then tezos-signer is not signing anything.... IT detects the 10 missing rewards which means the RPC API is working right? is just the signer is not receiving any signal from TRD to make the payments. Any idea?

**Comment by logart89** [comment]
I dont know if this relevant but i cant even create a new configuration file 

``` logart@logart2:~/code/tezos-reward-distributor$ python3 src/configure.py
 _____ ______ ______
|_   _|| ___ \|  _  \
  | |  | |_/ /| | | |
  | |  |    / | | | |
  | |  | |\ \ | |/ /
  \_/  \_| \_||___/

--------------------------------------------
Copyright Huseyin ABANOZ 2019
huseyinabanox@gmail.com
Please leave copyright information
--------------------------------------------
2020-01-24 19:06:43,510 - MainThread - Tezos Reward Distributor Baker Configuration Tool is Starting
2020-01-24 19:06:43,511 - MainThread - Arguments Configuration = {
 "reward_data_provider": "prpc",
 "network": "MAINNET",
 "reports_base": "~/pymnt/reports",
 "config_dir": "~/pymnt/cfg",
 "node_addr": "127.0.0.1:8732",
 "executable_dirs": "~/,~/tezos",
 "docker": false,
 "verbose": false,
 "dry_run": false
}
Traceback (most recent call last):
  File "src/configure.py", line 493, in <module>
    main(args)
  File "src/configure.py", line 374, in main
    config_client_manager = SimpleClientManager(client_path)
TypeError: __init__() missing 1 required positional argument: 'node_addr'
