### ISSUE TITLE
Configuration tools not working.

### ISSUE THREAD

**Issue by logart89** [habanoz/tezos-reward-distributor#195]
```
logart@logart2:~/code/tezos-reward-distributor$ python3 src/configure.py
 _____ ______ ______
|_   _|| ___ \|  _  \
  | |  | |_/ /| | | |
  | |  |    / | | | |
  | |  | |\ \ | |/ /
  \_/  \_| \_||___/

--------------------------------------------
Copyright Huseyin ABANOZ 2019
huseyinabanox@gmail.com
Please leave copyright information
--------------------------------------------
2020-02-04 17:58:16,820 - MainThread - Tezos Reward Distributor Baker Configuration Tool is Starting
2020-02-04 17:58:16,820 - MainThread - Arguments Configuration = {
 "reward_data_provider": "prpc",
 "network": "MAINNET",
 "reports_base": "~/pymnt/reports",
 "config_dir": "~/pymnt/cfg",
 "node_addr": "127.0.0.1:8732",
 "executable_dirs": "~/,~/tezos",
 "docker": false,
 "verbose": false,
 "dry_run": false
}
Traceback (most recent call last):
  File "src/configure.py", line 493, in <module>
    main(args)
  File "src/configure.py", line 374, in main
    config_client_manager = SimpleClientManager(client_path)
TypeError: __init__() missing 1 required positional argument: 'node_addr'


```
Please help me to fix this, i need to set up a founders or owners or supporters in the yaml file so my family get the full reward (0%) fee. And i have no idea how to do it without the configuration tool. Thanks

**Comment by utdrmac** [comment]
Will submit PR shortly
