### ISSUE TITLE
API provider call failed

### ISSUE THREAD

**Issue by songproducer** [habanoz/tezos-reward-distributor#199]
Hi,

I am trying to do payouts with unfrozen rewards:
python3 src/main.py -C 199 -P tzstats -R -5

but I suspect something is not happy with tzstats api

```
2020-02-11 13:53:41,141 - MainThread - --------------------------------------------
2020-02-11 13:53:41,141 - MainThread - BAKING ADDRESS is tz1egbN6RK2bM5vt4aAZw6r9j4nL8z49bPdS
2020-02-11 13:53:41,141 - MainThread - PAYMENT ADDRESS is tz1bd5Pn5DxPinvCtkeJmoneyYiLeUebvUa5
2020-02-11 13:53:41,141 - MainThread - --------------------------------------------
2020-02-11 13:53:41,142 - MainThread - Producer "producer" started
2020-02-11 13:53:41,142 - producer_retry_fail - Retry Fail thread "producer_retry_fail" started
2020-02-11 13:53:41,146 - MainThread - If you want to send emails, populate email.ini file under current working directory.
2020-02-11 13:53:41,146 - MainThread - Consumer "consumer0" created
2020-02-11 13:53:42,148 - MainThread - Application start completed
2020-02-11 13:53:42,148 - MainThread - --------------------------------------------
2020-02-11 13:53:52,008 - producer  - Checking for pending payments : checking 199 <= 200 - (5 + 1) - -5
2020-02-11 13:53:52,008 - producer  - Please note that you are doing payouts for frozen rewards!!!
2020-02-11 13:53:52,008 - producer  - Payment cycle is 199
2020-02-11 13:53:57,965 - producer  - API provider call failed, will try again.
2020-02-11 13:54:14,682 - producer  - Checking for pending payments : checking 199 <= 200 - (5 + 1) - -5
2020-02-11 13:54:14,682 - producer  - Please note that you are doing payouts for frozen rewards!!!
2020-02-11 13:54:14,683 - producer  - Payment cycle is 199
2020-02-11 13:55:56,365 - producer  - Error at payment producer loop, will try again.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/leo/.local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/leo/tezos-reward-distributor/src/pay/payment_producer.py", line 225, in try_to_pay
    reward_model = self.reward_api.get_rewards_for_cycle_map(pymnt_cycle)
  File "/home/leo/tezos-reward-distributor/src/tzstats/tzstats_reward_api.py", line 22, in get_rewards_for_cycle_map
    root = self.helper.get_rewards_for_cycle(cycle, expected_reward, self.verbose)
  File "/home/leo/tezos-reward-distributor/src/tzstats/tzstats_reward_provider_helper.py", line 164, in get_rewards_for_cycle
    resp = requests.get(uri, timeout=5)
  File "/home/leo/.local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/leo/.local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/leo/.local/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/leo/.local/lib/python3.7/site-packages/requests/sessions.py", line 659, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/leo/.local/lib/python3.7/site-packages/requests/sessions.py", line 659, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/leo/.local/lib/python3.7/site-packages/requests/sessions.py", line 238, in resolve_redirects
    **adapter_kwargs
  File "/home/leo/.local/lib/python3.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/leo/.local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

```

**Comment by songproducer** [comment]
Tried again today and it works
