### ISSUE TITLE
Error generating report

### ISSUE THREAD

**Issue by knd** [habanoz/tezos-reward-distributor#216]
**Describe the bug**
Error when trying to generate report

**To Reproduce**
1. Command:

```
python3 src/main.py -C 217 -M 3 -Dc -P rpc -A 127.0.0.1:8733 -V
```

**Expected behavior**
Should generate report in `~/pymnt/reports` without error.

**Screenshots**
```
2020-04-21 16:24:28,614 - MainThread - Producer "producer" started
2020-04-21 16:24:33,670 - producer  - Checking for pending payments : checking 217 <= 224 - (5 + 1) - 0
2020-04-21 16:24:33,670 - producer  - Payment cycle is 217
2020-04-21 16:24:33,911 - producer  - Error at payment producer loop, will try again.
Traceback (most recent call last):
  File "/home/tai/tezos-reward-distributor/src/pay/payment_producer.py", line 225, in try_to_pay
	reward_model = self.reward_api.get_rewards_for_cycle_map(pymnt_cycle)
  File "/home/tai/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 39, in get_rewards_for_cycle_map
	"delegators"] = self.__get_delegators_and_delgators_balances(cycle, current_level)
  File "/home/tai/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 123, in __get_delegators_and_delgators_balances
	hash_snapshot_block = self.__get_snapshot_block_hash(cycle, current_level)
  File "/home/tai/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 203, in __get_snapshot_block_hash
	chosen_snapshot = self.do_rpc_request(request)
  File "/home/tai/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 105, in do_rpc_request
	raise Exception("Request '{} failed with status code {}, after {}, unique request_id {}".format(request, resp.status_code, time_out, resp.headers['CF-RAY']))
  File "/home/tai/.local/lib/python3.6/site-packages/requests/structures.py", line 52, in __getitem__
	return self._store[key.lower()][1]
KeyError: 'cf-ray'

```

**Environment**
 - Source Code Build
 - Chain mainnet
 - actual command used

```
python3 src/main.py -C 217 -M 3 -Dc -P rpc -A 127.0.0.1:8733 -V
```

**Comment by utdrmac** [comment]
@knd Are you still experiencing this issue? This error happens when TRD is unable to fetch data via certain HTTP calls. We should add some better error handling here.
