### ISSUE TITLE
getting errors sending payout

### ISSUE THREAD

**Issue by issie81** [habanoz/tezos-reward-distributor#38]
i am getting error payout

9-02-07 12:52:10,214 - main - DEBUG - producer  - Checking for pending payments : payment_cycle <= current_cycle - (self.nw_config['NB_FREEZE_CYCLE'] + 1) - self.release_override
2019-02-07 12:52:10,214 - main - DEBUG - producer  - Checking for pending payments : checking 68 <= 74 - (5 + 1) - 0
2019-02-07 12:52:10,214 - main - INFO - producer  - Payment cycle is 68
2019-02-07 12:52:10,642 - main - INFO - producer  - Total rewards=976.01381
2019-02-07 12:52:10,642 - main - INFO - consumer0 - Starting payments for cycle 68
2019-02-07 12:52:10,643 - main - INFO - producer  - Reward created for cycle 68 address xxamount -3.866000 fee 4.510169 tz type D
2019-02-07 12:52:10,644 - main - INFO - producer  - Reward created for cycle 68 address xx amount -0.528000 fee 0.615841 tz type D
2019-02-07 12:52:10,645 - main - INFO - producer  - Reward creation done for cycle 68
2019-02-07 12:52:10,911 - main - DEBUG - consumer0 - Payment will be done in 1 batches
2019-02-07 12:52:10,911 - main - DEBUG - consumer0 - Payment of a batch started
2019-02-07 12:52:11,392 - main - DEBUG - consumer0 - head: branch xxcounter 12 protocol xx
2019-02-07 12:52:11,392 - main - DEBUG - consumer0 - Running 0 operations
2019-02-07 12:52:11,624 - main - DEBUG - consumer0 - Forging 0 operations
2019-02-07 12:52:11,856 - main - ERROR - consumer0 - Error at reward payment
Traceback (most recent call last):
  File "/home/payment/xx/tezos-reward-distributor/src/pay/payment_consumer.py", line 70, in run
    payment_logs = batch_payer.pay(payment_items, self.verbose, dry_run=self.dry_run)
  File "/home/payment/xx/tezos-reward-distributor/src/pay/batch_payer.py", line 79, in pay
    payments_log = self.pay_single_batch_wrap(payment_items_chunk, verbose=verbose, dry_run=dry_run)
  File "/home/payment/xx/tezos-reward-distributor/src/pay/batch_payer.py", line 94, in pay_single_batch_wrap
    return_code, operation_hash = self.pay_single_batch(payment_items, verbose, dry_run=dry_run)
  File "/home/payment/xx/tezos-reward-distributor/src/pay/batch_payer.py", line 175, in pay_single_batch
    bytes = parse_json_response(forge_command_response, verbose=verbose)
  File "/home/payment/xx/tezos-reward-distributor/src/util/rpc_utils.py", line 16, in parse_json_response
    raise Exception("Unknown client response format")
Exception: Unknown client response format

what can this be?

**Comment by issie81** [comment]
not that both payouts are negative, can this be the reason for error?
do i maybe need to run from first cycle i can pay? like 63 i think somewhere along something went wrong with setting all up

**Comment by habanoz** [comment]
Please your BussinessConfiguration you may shadow addresses.

**Comment by habanoz** [comment]
This looks like a service fee ratio problem. If you have your service fee %4.5 it should be set to 0.045.

Please adjust your settings.

**Comment by issie81** [comment]
Omg i am not behind computer but i know fee is set at 7.00 hence the negative fees

I will set at 0.07 (7%)
Is there a way to restart payment/calculations since previous ones are not correct

**Comment by habanoz** [comment]
Run the application again.  Closing this issue.

--
BussinessConfiguration file has example content. You can make use of it.

https://github.com/habanoz/tezos-reward-distributor/blob/master/src/BusinessConfiguration.py

**Comment by issie81** [comment]
ok i also did git pull for latest update, still getting some errors!
the payments are now positive

2019-02-08 12:29:53,975 - main - DEBUG - MainThread - Client command is /home/payment/tezos/tezos-client
2019-02-08 12:29:53,975 - main - INFO - MainThread - initial_cycle set to 68
2019-02-08 12:29:53,975 - main - DEBUG - MainThread - Producer started
2019-02-08 12:29:53,976 - main - INFO - MainThread - If you want to send emails, populate email.ini file under current working directory.
2019-02-08 12:29:53,976 - main - DEBUG - MainThread - Consumer "consumer0" created
2019-02-08 12:29:59,045 - main - DEBUG - producer  - Trying payments for cycle 68
2019-02-08 12:29:59,095 - main - DEBUG - producer  - Checking for pending payments : payment_cycle <= current_cycle - (self.nw_config['NB_FREEZE_CYCLE'] + 1) - self.release_override
2019-02-08 12:29:59,095 - main - DEBUG - producer  - Checking for pending payments : checking 68 <= 74 - (5 + 1) - 0
2019-02-08 12:29:59,095 - main - INFO - producer  - Payment cycle is 68
2019-02-08 12:29:59,441 - main - INFO - producer  - Total rewards=976.01381
2019-02-08 12:29:59,441 - main - INFO - consumer0 - Starting payments for cycle 68
2019-02-08 12:29:59,445 - main - INFO - producer  - Reward created for cycle 68 address xxamount 0.599000 fee 0.045169 tz type D
2019-02-08 12:29:59,446 - main - INFO - producer  - Reward created for cycle 68 address xxamount 0.081000 fee 0.006841 tz type D
2019-02-08 12:29:59,446 - main - INFO - producer  - Reward creation done for cycle 68
2019-02-08 12:29:59,714 - main - DEBUG - consumer0 - Payment will be done in 1 batches
2019-02-08 12:29:59,714 - main - DEBUG - consumer0 - Payment of a batch started
2019-02-08 12:30:00,194 - main - DEBUG - consumer0 - head: branch xxcounter 12 protocol PsddFKi32cMJ2qPjf43Qv5GDWLDPZb3T3bF6fLKiF5HtvHNU7aP
2019-02-08 12:30:00,194 - main - INFO - consumer0 - Payment content: {"kind":"transaction","source":"xx","destination":"xx","fee":"1274","counter":"13","gas_limit": "10100", "storage_limit": "0","amount":"599000"}
2019-02-08 12:30:00,194 - main - INFO - consumer0 - Payment content: {"kind":"transaction","source":"xx","destination":"xx","fee":"1274","counter":"14","gas_limit": "10100", "storage_limit": "0","amount":"81000"}
2019-02-08 12:30:00,194 - main - DEBUG - consumer0 - Running 2 operations
2019-02-08 12:30:00,423 - main - DEBUG - consumer0 - Forging 2 operations
2019-02-08 12:30:00,888 - main - ERROR - consumer0 - Error at reward payment
Traceback (most recent call last):
  File "/home/payment/Dropbox/tezos-reward-distributor/src/pay/payment_consumer.py", line 70, in run
    payment_logs = batch_payer.pay(payment_items, self.verbose, dry_run=self.dry_run)
  File "/home/payment/xx/tezos-reward-distributor/src/pay/batch_payer.py", line 79, in pay
    payments_log = self.pay_single_batch_wrap(payment_items_chunk, verbose=verbose, dry_run=dry_run)
  File "/home/payment/xx/tezos-reward-distributor/src/pay/batch_payer.py", line 94, in pay_single_batch_wrap
    return_code, operation_hash = self.pay_single_batch(payment_items, verbose, dry_run=dry_run)
  File "/home/payment/xx/tezos-reward-distributor/src/pay/batch_payer.py", line 176, in pay_single_batch
    signed_bytes = sign(self.client_path, bytes, self.key_name)
  File "/home/payment/xx/tezos-reward-distributor/src/util/client_utils.py", line 158, in sign
    raise Exception("Signature not found in response ''".format(response))
Exception: Signature not found in response ''

**Comment by habanoz** [comment]
Please make sure private key for the payment address is imported. If the client does not know the private key, it cannot sign the transactions.

**Comment by issie81** [comment]
Hello Sir,

i am allready doing that

![image](https://user-images.githubusercontent.com/35930081/52484224-19e52280-2bb6-11e9-9b94-5d459e068fd0.png)

as you can see al is imported (unencrypted)

![image](https://user-images.githubusercontent.com/35930081/52484457-a7c10d80-2bb6-11e9-9660-626d5c175f96.png)

i even reinstalled my whole node (did quicksync) now still get similar errors
atleast i got the negative values out of the way now

as you can see it says total rewards is 976.01381
yet i makes less payout because i didnt set founder and deposit map this shouldnt be the issue right?

![image](https://user-images.githubusercontent.com/35930081/52484705-4f3e4000-2bb7-11e9-8721-ba3b52c186eb.png)

**Comment by habanoz** [comment]
I made a small change. Please update and run the same command. Then share the log, please.

Error response coming from the client will be printed like below:

Signature not found in response 'client response here'

**Comment by issie81** [comment]
did git pull now:

Traceback (most recent call last):
  File "/home/payment/Dropbox/tezos-reward-distributor/src/pay/payment_consumer.py", line 70, in run
    payment_logs = batch_payer.pay(payment_items, self.verbose, dry_run=self.dry_run)
  File "/home/payment/Dropbox/tezos-reward-distributor/src/pay/batch_payer.py", line 79, in pay
    payments_log = self.pay_single_batch_wrap(payment_items_chunk, verbose=verbose, dry_run=dry_run)
  File "/home/payment/Dropbox/tezos-reward-distributor/src/pay/batch_payer.py", line 94, in pay_single_batch_wrap
    return_code, operation_hash = self.pay_single_batch(payment_items, verbose, dry_run=dry_run)
  File "/home/payment/Dropbox/tezos-reward-distributor/src/pay/batch_payer.py", line 176, in pay_single_batch
    signed_bytes = sign(self.client_path, bytes, self.key_name)
  File "/home/payment/Dropbox/tezos-reward-distributor/src/util/client_utils.py", line 158, in sign
    raise Exception("Signature not found in response '{}'".format(response))
Exception: Signature not found in response ''

**Comment by habanoz** [comment]
Nothing useful here. The response seems to be empty. You will need to run sign command yourself and share the results. 

I made another update, please pull it and run with -V command. There you will see the sign command. If you cannot see, you may share the log. 

Run that command and see the client response. It will probably reveal what is wrong.

**Comment by issie81** [comment]
done lets hope this is usefull

![image](https://user-images.githubusercontent.com/35930081/52518327-66c60900-2c49-11e9-8d5c-0d303c24b1cc.png)

**Comment by habanoz** [comment]
Please have a look, it may help:

https://www.reddit.com/r/tezos/comments/aa5lr3/cant_deploy_a_contract_please_help/

Are you using tz or kt address?

**Comment by issie81** [comment]
hmm this is strange, the tz1 works and the kt1 doenst
both have alias, as suggested i imported the unencrypted private key of the tz1
then justed your suggested

tezos-client remember contract new src

why wouldnt kt1 not work? its originated from the tz1
i have to say i have set the kt1 to use my baker as delegator surely this cant be the problem

**Comment by habanoz** [comment]
My guess is when paying with kt address it is required to sign with manager account. 

Please open an issue for kt payment support. 

Meanwhile please use tz address for payments.

If everything is ok, you may close this issue.
