### ISSUE TITLE
V3 Migration

### ISSUE THREAD

**Issue by SemElVik** [habanoz/tezos-reward-distributor#49]
When importing v3, 2 folders are created in the home directory.
1. pymnt - cnfg - tz1.... .yaml
2. tezos-reward-distributor-v3  - there is also tz1boot1 ..... 889 .yaml file

I edited the file imported from version 2.1 which is in the folder: pymnt - cnfg - tz1..yaml
but failed to start the dry mode.
where is the mistake? It seems to me in the configuration of the .yaml file.  
What should I indicate in my billing address, alias or address?

the same file tz1boot1.....889.yaml is found as an example, as I understand it?

**Comment by SemElVik** [comment]
`tz@tz:~/tezos-reward-distributor-v3$ python3 src/main.py -D -M 3 -C 70
2019-02-15 01:14:49,413 - main - INFO - MainThread - Tezos Reward Distributor is Starting
2019-02-15 01:14:49,413 - main - INFO - MainThread - --------------------------------------------
2019-02-15 01:14:49,414 - main - INFO - MainThread - Copyright Hüseyin ABANOZ 2019
2019-02-15 01:14:49,414 - main - INFO - MainThread - huseyinabanox@gmail.com
2019-02-15 01:14:49,414 - main - INFO - MainThread - Please leave copyright information
2019-02-15 01:14:49,414 - main - INFO - MainThread - --------------------------------------------
2019-02-15 01:14:49,414 - main - INFO - MainThread - DRY RUN MODE
2019-02-15 01:14:49,414 - main - INFO - MainThread - --------------------------------------------
2019-02-15 01:14:49,414 - main - INFO - MainThread - Arguments Configuration = {
 "network": "MAINNET",
 "reports_dir": "~/pymnt/reports",
 "config_dir": "~/pymnt/cfg",
 "node_addr": "127.0.0.1:8732",
 "dry_run": true,
 "dry_run_no_payments": false,
 "executable_dirs": "~/,~/tezos",
 "docker": false,
 "verbose": false,
 "run_mode": 3,
 "release_override": 0,
 "payment_offset": 0,
 "initial_cycle": 70
}
2019-02-15 01:14:49,414 - main - INFO - MainThread - master configuration file not present.
2019-02-15 01:14:49,415 - main - DEBUG - MainThread - Tezos client path is /home/tz/tezos/tezos-client
2019-02-15 01:14:49,415 - main - INFO - MainThread - Loading baking configuration file /home/tz/pymnt/cfg/tz1------------.yaml
Traceback (most recent call last):
  File "src/main.py", line 252, in <module>
    main(args)
  File "src/main.py", line 86, in main
    parser.parse()
  File "/home/tz/tezos-reward-distributor-v3/src/config/yaml_baking_conf_parser.py", line 19, in parse
    yaml_conf_dict = super().parse()
  File "/home/tz/tezos-reward-distributor-v3/src/config/yaml_conf_parser.py", line 11, in parse
    self.set_conf_obj(yaml.safe_load(self.conf_text))
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 1, column 1:
    baking_address: tz1----------6 ...
    ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 3, column 3:
      ? ''
      ^`

**Comment by SemElVik** [comment]
the .yaml file looks like this 
```baking_address: tz1------------------
excluded_delegators_set: {}
  ? ''
  : null
founders_map:
  KT1--------------: 0.3400934435
  KT1--------------: 0.319813113
  KT1--------------: 0.3400934435
min_delegation_amt: 0.0
owners_map:
  KT1-----: 0.3400934435
  KT1-----: 0.319813113
  KT1-----: 0.3400934435
payment_address: tzPay
prcnt_scale: None
pymnt_scale: None
service_fee: 7.00
specials_map: {}
supporters_set: {}
  ? ''
  : null
version: '1.0'```

**Comment by SemElVik** [comment]
I edited the file. everything went perfectly.
looks like that: 
```baking_address: tz1enRFEJ6w91Q665UfMfxK4YT4sgZZ7iJYQ
payment_address : tzPay
excluded_delegators_set: {}
founders_map:
  KT1---: 0.3400934435
  KT1---: 0.319813113
  KT1---: 0.3400934435
min_delegation_amt: 0.0
owners_map:
  KT1---: 0.3400934435
  KT1---: 0.319813113
  KT1---: 0.3400934435
prcnt_scale: None
pymnt_scale: None
service_fee: 7.00
specials_map: {}
supporters_set: {}
delegator_pays_xfer_fee : False
version: '1.0'```

**Comment by habanoz** [comment]
Did you use migration script? What did you changed in the yaml file? What was the cause of the false input: migration script output or user edit ?

**Comment by SemElVik** [comment]
Yes, it was a migration script. everything went well.
there was a missing line in the .yaml file : `delegator_pays_xfer_fee : False` 
as well as I removed the lines in file .yaml: `? ''
  : null `

these are extra lines where: ```
supporters_set: {}
  ? ''
  : null
```
+
```
excluded_delegators_set: {}
  ? ''
  : null
```

**Comment by SemElVik** [comment]
I did not save the original .yaml migration file, but it looked like this: 
```
baking_address: tz1-------------
excluded_delegators_set: {}
  ? ''
  : null
founders_map:
  KT1-----------------: 0.3400934435
  KT1-----------------: 0.319813113
  KT1-----------------: 0.3400934435
min_delegation_amt: 0.0
owners_map:
  KT1-----------------: 0.3400934435
  KT1-----------------: 0.319813113
  KT1-----------------: 0.3400934435
payment_address: paymentaddresses
prcnt_scale: None
pymnt_scale: None
service_fee: 7.0000000001
specials_map: {}
supporters_set: {}
  ? ''
  : null
version: '1.0'
```
