### ISSUE TITLE
Error sending dry-run payment

### ISSUE THREAD

**Issue by DaylightCulture** [habanoz/tezos-reward-distributor#55]
**Describe the bug**

Recieving an Unexpected server answer when running:
~/tezos-reward-distributor$ python3 src/main.py -C 58 -M 3 -D -V
Running version 3

**To Reproduce**
1. ran this command:
~/tezos-reward-distributor$ python3 src/main.py -C 58 -M 3 -D -V

2. My config file looks like this:

version : 1.0
baking_address : tzxxxxBAKERADDRESSxxxxxx
payment_address : tzxxxPAYMENTADDRESSxxxx
service_fee : 8.0
founders_map : {}
owners_map : {}
prcnt_scale : None
pymnt_scale : None
specials_map : {}
supporters_set : {}
min_delegation_amt : 0
excluded_delegators_set : {}
delegator_pays_xfer_fee : True

3. See error

Answer is |Unexpected server answer
|
2019-02-26 15:12:26,857 - main - ERROR - consumer0 - Error at reward payment
Traceback (most recent call last):
 File "/home/b/tezos-reward-distributor/src/pay/payment_consumer.py", line 72, in run
   payment_logs = batch_payer.pay(payment_items, self.verbose, dry_run=self.dry_run)
 File "/home/b/tezos-reward-distributor/src/pay/batch_payer.py", line 96, in pay
   payments_log = self.pay_single_batch_wrap(payment_items_chunk, verbose=verbose, dry_run=dry_run)
 File "/home/b/tezos-reward-distributor/src/pay/batch_payer.py", line 111, in pay_single_batch_wrap
   return_code, operation_hash = self.pay_single_batch(payment_items, verbose, dry_run=dry_run)
 File "/home/b/tezos-reward-distributor/src/pay/batch_payer.py", line 172, in pay_single_batch
   error_desc = parse_json_response(runops_command_response)
 File "/home/b/tezos-reward-distributor/src/util/rpc_utils.py", line 16, in parse_json_response
   raise Exception("Unknown client response format")
Exception: Unknown client response format
2019-02-26 15:12:26,858 - main - DEBUG - consumer0 - Exit signal received. Killing the thread...
2019-02-26 15:12:26,858 - main - INFO - consumer0 - Consumer returning ...
2019-02-26 15:12:30,132 - main - INFO - MainThread - Interrupted.
2019-02-26 15:12:30,133 - main - INFO - MainThread - --------------------------------------------------------
2019-02-26 15:12:30,133 - main - INFO - MainThread - Sensitive operations are in progress!
2019-02-26 15:12:30,134 - main - INFO - MainThread - Please wait while the application is being shut down!
2019-02-26 15:12:30,134 - main - INFO - MainThread - --------------------------------------------------------

**Comment by SemElVik** [comment]
look at a couple of things:
- your address must be disclosed;
- your address balance must have a payment amount  (+ a bit more)

**Comment by habanoz** [comment]
I added a check for revelations. If the payment address is not revealed, the application will not start. 

Please update and see if you have any issue with revelations. 

If your problem is not about revelation, run the application with -V switch. You will see the command which fails. You may run it in command line to see what is wrong. 

Please share your results.

**Comment by DaylightCulture** [comment]
Revealing the address worked for me. The address was not revealed at the time.

2019-02-27 16:28:05,689 - main - DEBUG - consumer0 - Payment of a batch is complete
2019-02-27 16:28:05,690 - main - INFO - consumer0 - Reward paid for cycle 58 address KT1
amount 200 tz type D
2019-02-27 16:28:05,690 - main - DEBUG - consumer0 - Exit signal received. Killing the thread...
2019-02-27 16:28:05,690 - main - INFO - consumer0 - Consumer returning ...

**Comment by habanoz** [comment]
Looks all right. Closing. You may reopen if the problem persists.
