### ISSUE TITLE
Transactions fail after python update

### ISSUE THREAD

**Issue by amani1104** [habanoz/tezos-reward-distributor#59]
**Describe the bug**
After updating Ubuntu the Tezos Reward Distributor does not work any longer. I noticed that there was a python 3 update among the other updates, so the issue may be related to it.

This is what I get when running the software:
 
2019-03-06 14:44:48,184 - main - INFO - MainThread - --------------------------------------------
2019-03-06 14:44:48,184 - main - INFO - MainThread - BAKING ADDRESS is tz1… 
2019-03-06 14:44:48,185 - main - INFO - MainThread - PAYMENT ADDRESS is payout
2019-03-06 14:44:48,185 - main - INFO - MainThread - --------------------------------------------
2019-03-06 14:44:48,185 - main - DEBUG - MainThread - Producer started
Traceback (most recent call last):
  File "src/main.py", line 254, in <module>
    main(args)
  File "src/main.py", line 149, in main
    delegator_pays_xfer_fee=cfg.get_delegator_pays_xfer_fee())
  File "/home/tezos/tezos-reward-distributor/src/pay/payment_consumer.py", line 40, in __init__
    self.mm = EmailManager()
  File "/home/tezos/tezos-reward-distributor/src/emails/email_manager.py", line 33, in __init__
    if self.all_set(default):
  File "/home/tezos/tezos-reward-distributor/src/emails/email_manager.py", line 40, in all_set
    return default[USER] and default[PASS] and default[HOST] and default[PORT] and default[SENDER] and default[
  File "/usr/lib/python3.6/configparser.py", line 1234, in __getitem__
    return self._parser.get(self._name, key)
  File "/usr/lib/python3.6/configparser.py", line 800, in get
    d)
  File "/usr/lib/python3.6/configparser.py", line 394, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.6/configparser.py", line 444, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: 'XXXXXXXX'
2019-03-06 14:44:53,612 - main - DEBUG - producer  - Trying payments for cycle 77
2019-03-06 14:44:53,973 - main - DEBUG - producer  - Checking for pending payments : payment_cycle <= current_cycle - (self.nw_config['NB_FREEZE_CYCLE'] + 1) - self.release_override
2019-03-06 14:44:53,973 - main - DEBUG - producer  - Checking for pending payments : checking 77 <= 83 - (5 + 1) - 0
2019-03-06 14:44:53,973 - main - INFO - producer  - Payment cycle is 77
2019-03-06 14:44:54,710 - main - INFO - producer  - Total rewards=30.00276
2019-03-06 14:44:54,711 - main - INFO - producer  - Reward created for cycle 77 address KT1… amount 10.004000 fee 0.526969 tz type D
2019-03-06 14:44:54,711 - main - INFO - producer  - Reward created for cycle 77 address KT1… amount 0.000000 fee 0.000000 tz type D
2019-03-06 14:44:54,711 - main - INFO - producer  - Reward created for cycle 77 address KT1… amount 19.471000 fee 0.000000 tz type O
2019-03-06 14:44:54,711 - main - INFO - producer  - Reward creation done for cycle 77
2019-03-06 14:44:54,712 - main - INFO - producer  - Run mode ONETIME satisfied. Killing the thread ...
2019-03-06 14:44:54,712 - main - INFO - producer  - Producer returning ...
Exception ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
 
Although the log states that the outputs were created that's not the case, as transfers have not been processed.  

**To Reproduce**

`python3 src/main.py -C 77 -M 3`

**Environment**
 - Source Code Build
 - Chain mainnet

**Comment by habanoz** [comment]
Looks like you have populated email.ini. Your password contains '%' char which confuses the configurator. Try changing your password, or escape '%' with another '%'.

Note that I have replaced your password with XXXX.

Closing. Please, reopen if the problem persists.

**Comment by amani1104** [comment]
You are right. Replacing the password to another one without '%' solved this issue. Thank you!
