### ISSUE TITLE
tezos-signer error (unix socket)

### ISSUE THREAD

**Issue by Z1Quest** [habanoz/tezos-reward-distributor#77]
first, thanks for your contribution, TRD is a great tool 

current setup: tezos-signer (unix socket), works perfectly fine manually. using TRD getting the following error. 

_**#  File "/home/tezz/tezos-reward-distributor/src/cli/wallet_client_manager.py", line 71, in get_addr_dict_by_pkh
    _raise ClientException("Address(PKH) {} is not imported to client. Import it first.".format(pkh))
exception.client.ClientException: Address(PKH) tz1XXXX is not imported to client. Import it first.****__

Does TRD  work with all signing scheme supported by the client? (tcp, unix, http, https)?

Thanks!

**Comment by habanoz** [comment]
TRD should be unaware of the underlying schema.

TRD is tested with "unencrypted sk known", "tcp sk known" and "unencrypted sk not known".

If you can provide "tezos-client list known addresses" output I may test for other schemas.

**Comment by habanoz** [comment]
Do you use docker version?

**Comment by Z1Quest** [comment]
No, not using docker. Will send output of command above shortly

**Comment by Z1Quest** [comment]
here's the output of "tezos-client known addresses" :  it lists the delegate tz1 address

Disclaimer:
  The  Tezos  network  is  a  new  blockchain technology.
  Users are  solely responsible  for any risks associated
  with usage of the Tezos network.  Users should do their
  own  research to determine  if Tezos is the appropriate
  platform for their needs and should apply judgement and
  care in their network interactions.

baker: tz1XXXXXXXX  (unix sk known)

**Comment by habanoz** [comment]
This schema is parsed correctly. Something else needs to be wrong. 

Check your log file, there must be a line "Generating known address dictionary" which needs to be followed by "Known address added" or "Known contract added" statements. 

Those lines may provide more information.

**Comment by Z1Quest** [comment]
nothing in log files, ran script multiple times. I Even changed the node logging parameters to debug, restarted still nothing.

**Comment by habanoz** [comment]
Not the node log, I mean the app.log. Did you check app.log file as well.

**Comment by Z1Quest** [comment]
Here's the app.log 

2019-05-21 15:15:16,812 - main - INFO - MainThread - Loading master configuration file /home/tezz/pymnt/cfg/master.yaml
2019-05-21 15:15:16,813 - main - DEBUG - MainThread - Tezos client path is /home/tezz/bin-main/tezos-client
2019-05-21 15:15:16,816 - main - INFO - MainThread - Failed to get network configuration constants from a local node.
2019-05-21 15:15:17,158 - main - INFO - MainThread - Network configuration constants successfully loaded from a public node.
2019-05-21 15:15:17,159 - main - INFO - MainThread - Loading baking configuration file /home/tezz/pymnt/cfg/tz1XXXXXXXXXXXXXXX.yaml
2019-05-21 15:15:20,941 - main - DEBUG - MainThread - Available mirrors are: [1, 2, 3, 4, 5, 6]
2019-05-21 15:15:20,943 - main - DEBUG - MainThread - Generating known address dictionary

**Comment by habanoz** [comment]
This is weird. No useful information here. Can you run with -V switch and share the whole log with me.

**Comment by Z1Quest** [comment]
Here it is: 
2019-05-21 16:32:14,859 - main - INFO - MainThread - Tezos Reward Distributor is Starting
2019-05-21 16:32:14,860 - main - INFO - MainThread - --------------------------------------------
2019-05-21 16:32:14,860 - main - INFO - MainThread - Copyright Huseyin ABANOZ 2019
2019-05-21 16:32:14,860 - main - INFO - MainThread - huseyinabanox@gmail.com
2019-05-21 16:32:14,860 - main - INFO - MainThread - Please leave copyright information
2019-05-21 16:32:14,860 - main - INFO - MainThread - --------------------------------------------
2019-05-21 16:32:14,860 - main - INFO - MainThread - DRY RUN MODE
2019-05-21 16:32:14,860 - main - INFO - MainThread - --------------------------------------------
2019-05-21 16:32:14,860 - main - INFO - MainThread - Arguments Configuration = {
 "network": "MAINNET",
 "reward_data_provider": "tzscan",
 "reports_dir": "~/pymnt/reports",
 "config_dir": "~/pymnt/cfg",
 "node_addr": "127.0.0.1:8732",
 "dry_run": true,
 "dry_run_no_payments": false,
 "executable_dirs": "/home/tezos/bin-main/",
 "docker": false,
 "verbose": true,
 "run_mode": 1,
 "release_override": 0,
 "payment_offset": 0,
 "initial_cycle": null
}
2019-05-21 16:32:14,861 - main - INFO - MainThread - Loading master configuration file /home/tezz/pymnt/cfg/master.yaml
2019-05-21 16:32:14,862 - main - DEBUG - MainThread - Tezos client path is /home/tezz/bin-main/tezos-client
2019-05-21 16:32:14,864 - main - INFO - MainThread - Failed to get network configuration constants from a local node.
2019-05-21 16:32:15,193 - main - INFO - MainThread - Network configuration constants successfully loaded from a public node.
2019-05-21 16:32:15,193 - main - INFO - MainThread - Loading baking configuration file /home/tezos/pymnt/cfg/tz1VxbHcvqoiiZ3Fbc4oVeDhZQeoFRiWMaqN.yaml
2019-05-21 16:32:19,016 - main - DEBUG - MainThread - Available mirrors are: [1, 2, 3, 4, 5, 6]
2019-05-21 16:32:19,019 - main - DEBUG - MainThread - Generating known address dictionary
Traceback (most recent call last):
  File "src/main.py", line 261, in <module>
    main(args)
  File "src/main.py", line 92, in main
    parser.validate()
  File "/home/tezz/tezos-reward-distributor/src/config/yaml_baking_conf_parser.py", line 30, in validate
    self.__validate_payment_address(conf_obj)
  File "/home/tezz/tezos-reward-distributor/src/config/yaml_baking_conf_parser.py", line 103, in __validate_payment_address
    addr_obj = self.wllt_clnt_mngr.get_addr_dict_by_pkh(pymnt_addr)
  File "/home/tezz/tezos-reward-distributor/src/cli/wallet_client_manager.py", line 71, in get_addr_dict_by_pkh
    raise ClientException("Address(PKH) {} is not imported to client. Import it first.".format(pkh))
exception.client.ClientException: Address(PKH) tz1VxbHcvqoiiZ3Fbc4oVeDhZQeoFRiWMaqN is not imported to client. Import it first.

**Comment by habanoz** [comment]
Nothing useful. Can you share console output with -V switch. There has to be some clue.

**Comment by Z1Quest** [comment]
attached the console output with -V switch 


[trd.log](https://github.com/habanoz/tezos-reward-distributor/files/3205006/trd.log)

**Comment by habanoz** [comment]
commands are missing from verbose output. There should have been commands like:
```
Command is |C:\Users\7624/mainnet.sh client list known contracts|
Answer is *******
known contracts: {}
Command is |C:\Users\7624/mainnet.sh client list known addresses|
Answer is ******
known addresses: {}
```

This situation may be result of using master.yaml file. If master file contains any address information they are loade right away and node is not queried for actual address information. 

Please ensure that there is no master.yaml file present in cfg directory. master file for testing porpuses only. It is not for production use thus it is not documented and supported.

**Comment by Z1Quest** [comment]
You are correct. removing master.yaml from cfg dir did the trick. 

Appreciate your help. thanks!

**Comment by habanoz** [comment]
You are welcome. Happy baking.

Closing.

**Comment by gisele-igore** [comment]
|_   _|| ___ \|  _  \
  | |  | |_/ /| | | |
  | |  |    / | | | |
  | |  | |\ \ | |/ /
  \_/  \_| \_||___/

--------------------------------------------
Copyright Huseyin ABANOZ 2019
huseyinabanox@gmail.com
Please leave copyright information
--------------------------------------------
2020-11-26 13:56:09,198 - MainThread - Tezos Reward Distributor is Starting
2020-11-26 13:56:09,199 - MainThread - --------------------------------------------
2020-11-26 13:56:09,200 - MainThread - DRY RUN MODE
2020-11-26 13:56:09,200 - MainThread - --------------------------------------------
2020-11-26 13:56:09,201 - MainThread - TRD version 8.0 is running in interactive mode.
2020-11-26 13:56:09,202 - MainThread - Arguments Configuration = {
 "initial_cycle": 291,
 "run_mode": 3,
 "release_override": -1,
 "payment_offset": 0,
 "network": "MAINNET",
 "node_addr": "100.64.0.182",
 "reward_data_provider": "tzkt",
 "node_addr_public": "",
 "reports_base": "~/pymnt/reports",
 "config_dir": "~/pymnt/cfg",
 "dry_run": true,
 "dry_run_no_consumers": false,
 "executable_dirs": "/home/tezostrd/.local/bin/",
 "docker": false,
 "background_service": false,
 "do_not_publish_stats": false,
 "verbose": "on",
 "api_base_url": null,
 "retry_injected": false,
 "syslog": false,
 "log_file": "logs/app.log"
}
2020-11-26 13:56:09,202 - MainThread - Anonymous statistics will be collected. See docs/statistics.rst for more information.
2020-11-26 13:56:09,711 - MainThread - Loading baking configuration file /home/tezostrd/pymnt/cfg/tz1NMNQYrYrfNpmUqQrMhJypf6ovnaDZhJHM.yaml
2020-11-26 13:56:10,104 - MainThread - No known address info is reached. Check your environment. Try to run in privileged mode.
Traceback (most recent call last):
  File "src/main.py", line 257, in <module>
    main(args)
  File "src/main.py", line 105, in main
    parser.validate()
  File "/home/tezostrd/tezos-reward-distributor/src/config/yaml_baking_conf_parser.py", line 32, in validate
    self.validate_payment_address(conf_obj)
  File "/home/tezostrd/tezos-reward-distributor/src/config/yaml_baking_conf_parser.py", line 132, in validate_payment_address
    addr_obj = self.wllt_clnt_mngr.get_addr_dict_by_pkh(pymnt_addr)
  File "/home/tezostrd/tezos-reward-distributor/src/cli/wallet_client_manager.py", line 68, in get_addr_dict_by_pkh
    raise ClientException("Address(PKH) {} is not imported to client. Import it first.".format(pkh))
exception.client.ClientException: Address(PKH) tz1NMNQYrYrfNpmUqQrMhJypf6ovnaDZhJHM is not imported to client. Import it first.

**Comment by gisele-igore** [comment]
> |_ _|| ___ | _ | | | |_/ /| | | |
> | | | / | | | |
> | | | |\ \ | |/ /
> _/ _| _||___/
> 
> ## Copyright Huseyin ABANOZ 2019
> [huseyinabanox@gmail.com](mailto:huseyinabanox@gmail.com)
> Please leave copyright information
> 2020-11-26 13:56:09,198 - MainThread - Tezos Reward Distributor is Starting
> 2020-11-26 13:56:09,199 - MainThread - --------------------------------------------
> 2020-11-26 13:56:09,200 - MainThread - DRY RUN MODE
> 2020-11-26 13:56:09,200 - MainThread - --------------------------------------------
> 2020-11-26 13:56:09,201 - MainThread - TRD version 8.0 is running in interactive mode.
> 2020-11-26 13:56:09,202 - MainThread - Arguments Configuration = {
> "initial_cycle": 291,
> "run_mode": 3,
> "release_override": -1,
> "payment_offset": 0,
> "network": "MAINNET",
> "node_addr": "100.64.0.182",
> "reward_data_provider": "tzkt",
> "node_addr_public": "",
> "reports_base": "~/pymnt/reports", "config_dir": "~/pymnt/cfg",
> "dry_run": true,
> "dry_run_no_consumers": false,
> "executable_dirs": "/home/tezostrd/.local/bin/",
> "docker": false,
> "background_service": false,
> "do_not_publish_stats": false,
> "verbose": "on",
> "api_base_url": null,
> "retry_injected": false,
> "syslog": false,
> "log_file": "logs/app.log"
> }
> 2020-11-26 13:56:09,202 - MainThread - Anonymous statistics will be collected. See docs/statistics.rst for more information.
> 2020-11-26 13:56:09,711 - MainThread - Loading baking configuration file /home/tezostrd/pymnt/cfg/tz1NMNQYrYrfNpmUqQrMhJypf6ovnaDZhJHM.yaml
> 2020-11-26 13:56:10,104 - MainThread - No known address info is reached. Check your environment. Try to run in privileged mode.
> Traceback (most recent call last):
> File "src/main.py", line 257, in
> main(args)
> File "src/main.py", line 105, in main
> parser.validate()
> File "/home/tezostrd/tezos-reward-distributor/src/config/yaml_baking_conf_parser.py", line 32, in validate
> self.validate_payment_address(conf_obj)
> File "/home/tezostrd/tezos-reward-distributor/src/config/yaml_baking_conf_parser.py", line 132, in validate_payment_address
> addr_obj = self.wllt_clnt_mngr.get_addr_dict_by_pkh(pymnt_addr)
> File "/home/tezostrd/tezos-reward-distributor/src/cli/wallet_client_manager.py", line 68, in get_addr_dict_by_pkh
> raise ClientException("Address(PKH) {} is not imported to client. Import it first.".format(pkh))
> exception.client.ClientException: Address(PKH) tz1NMNQYrYrfNpmUqQrMhJypf6ovnaDZhJHM is not imported to client. Import it first.

" I have tried all proposed solutions but still bugging"
