### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by nurikabe** [habanoz/tezos-reward-distributor#85]
**Describe the bug**
Crash when loading yaml configuration file

**To Reproduce**
Running v4.5 no problem. 5.5 crashes:
```
 _____ ______ ______
|_   _|| ___ \|  _  \
  | |  | |_/ /| | | |
  | |  |    / | | | |
  | |  | |\ \ | |/ /
  \_/  \_| \_||___/

--------------------------------------------
Copyright Huseyin ABANOZ 2019
huseyinabanox@gmail.com
Please leave copyright information
--------------------------------------------
2019-06-11 11:56:26,806 - MainThread - Tezos Reward Distributor is Starting
2019-06-11 11:56:26,807 - MainThread - --------------------------------------------
2019-06-11 11:56:26,807 - MainThread - DRY RUN MODE
2019-06-11 11:56:26,807 - MainThread - --------------------------------------------
2019-06-11 11:56:26,807 - MainThread - TRD version 5.5 is running in interactive mode.
2019-06-11 11:56:26,807 - MainThread - Arguments Configuration = {
 "node_addr": "127.0.0.1:8732",
 "dry_run_no_consumers": false,
 "release_override": 0,
 "reports_base": "~/pymnt/reports",
 "verbose": false,
 "do_not_publish_stats": false,
 "executable_dirs": "~/,~/tezos",
 "initial_cycle": 109,
 "reward_data_provider": "tzscan",
 "dry_run": true,
 "docker": false,
 "network": "MAINNET",
 "run_mode": 1,
 "config_dir": "~/pymnt/cfg",
 "payment_offset": 0,
 "background_service": false
}
2019-06-11 11:56:31,551 - MainThread - Loading baking configuration file /home/tezos/pymnt/cfg/tz1xyz.yaml
Traceback (most recent call last):
  File "src/main.py", line 258, in <module>
    main(args)
  File "src/main.py", line 99, in main
    parser.validate()
  File "/home/tezos/tezos-reward-distributor/src/config/yaml_baking_conf_parser.py", line 27, in validate
    self.validate_payment_address(conf_obj)
  File "/home/tezos/tezos-reward-distributor/src/config/yaml_baking_conf_parser.py", line 119, in validate_payment_address
    addr_obj = self.wllt_clnt_mngr.get_addr_dict_by_pkh(pymnt_addr)
  File "/home/tezos/tezos-reward-distributor/src/cli/wallet_client_manager.py", line 66, in get_addr_dict_by_pkh
    self.generate_address_dict()
  File "/home/tezos/tezos-reward-distributor/src/cli/wallet_client_manager.py", line 82, in generate_address_dict
    self.contr_dict_by_alias = self.__list_known_contracts_by_alias()
  File "/home/tezos/tezos-reward-distributor/src/cli/wallet_client_manager.py", line 110, in __list_known_contracts_by_alias
    _, response = self.send_request(" list known contracts")
  File "/home/tezos/tezos-reward-distributor/src/cli/simple_client_manager.py", line 15, in send_request
    return self.cmd_manager.execute(whole_cmd, verbose_override, timeout=timeout)
  File "/home/tezos/tezos-reward-distributor/src/cli/cmd_manager.py", line 29, in execute
    output = check_output(cmd, shell=True, stderr=STDOUT, timeout=timeout, encoding='utf8')
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

**Environment**
 - Source, master
 - mainnet
 - `$ python3 src/main.py -C109 -M1 -D`

**Comment by habanoz** [comment]
encoding argument is not supported prior to python 3.6. You need to update your python version. Following guide can be useful. 

https://jcutrer.com/linux/upgrade-python37-ubuntu1810

I will update version control accordingly.

**Comment by nurikabe** [comment]
Yep, upgraded to Python 3.7.3. Thanks!
