### ISSUE TITLE
Failed payments - Exception: Unknown client response format

### ISSUE THREAD

**Issue by utdrmac** [habanoz/tezos-reward-distributor#86]
First time using v5. First time trying with RPC. 
Not seeing any useful debugging output even with `-V`

```
$ python36 src/main.py -f pymnt/cfg/ -r pymnt/reports/ -N MAINNET -E /home/bakebaker/nomadic/ -O 16 -C 111 -P rpc -V
 _____ ______ ______
|_   _|| ___ \|  _  \
  | |  | |_/ /| | | |
  | |  |    / | | | |
  | |  | |\ \ | |/ /
  \_/  \_| \_||___/

--------------------------------------------
Copyright Huseyin ABANOZ 2019
huseyinabanox@gmail.com
Please leave copyright information
--------------------------------------------
2019-06-13 23:32:09,194 - MainThread - Tezos Reward Distributor is Starting
2019-06-13 23:32:09,194 - MainThread - TRD version 5.5 is running in interactive mode.
2019-06-13 23:32:09,195 - MainThread - Arguments Configuration = {
 "network": "MAINNET",
 "reward_data_provider": "rpc",
 "reports_base": "pymnt/reports/",
 "config_dir": "pymnt/cfg/",
 "node_addr": "127.0.0.1:8732",
 "dry_run": false,
 "dry_run_no_consumers": false,
 "executable_dirs": "/home/bakebaker/nomadic/",
 "docker": false,
 "verbose": true,
 "background_service": false,
 "do_not_publish_stats": false,
 "run_mode": 1,
 "release_override": 0,
 "payment_offset": 16,
 "initial_cycle": 111
}
2019-06-13 23:32:13,331 - MainThread - Loading baking configuration file pymnt/cfg/tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1.yaml
2019-06-13 23:32:20,188 - MainThread - Baking Configuration {
 "master_dict": {},
 "cfg_dict": {
  "baking_address": "tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1",
  "delegator_pays_xfer_fee": true,
  "founders_map": {},
  "min_delegation_amt": 0.0,
  "owners_map": {},
  "payment_address": "tacccos",
  "rules_map": {
   "KT19bi9mhnXBytz2GLMuEcDvTU8c8MHs8Gm6": "TOB",
   "KT1C1Sp9yaM5ekGX3z9yvyTvWVoGq1p6Nu8t": "TOB",
   "KT1LcCS7HGDETUEQviCHxoVDuFAHb78S2siL": "TOB",
   "KT1RCFYfKnVqegbHHBMZwcm4XYHq6MnKQq31": "TOB",
   "KT1VnfXq6AMYoa4o8VHuLz4WYTVuHr8ANLSy": "TOB",
   "mindelegation": "TOB"
  },
  "service_fee": 8.0,
  "specials_map": {},
  "supporters_set": [],
  "__payment_address_type": null,
  "__payment_address_pkh": "tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1",
  "__payment_address_manager": "tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1",
  "__full_supporters_set": [],
  "__excluded_delegators_set_toe": [],
  "__excluded_delegators_set_tof": [],
  "__excluded_delegators_set_tob": [
   "KT1RCFYfKnVqegbHHBMZwcm4XYHq6MnKQq31",
   "KT1C1Sp9yaM5ekGX3z9yvyTvWVoGq1p6Nu8t",
   "mindelegation",
   "KT1LcCS7HGDETUEQviCHxoVDuFAHb78S2siL",
   "KT1VnfXq6AMYoa4o8VHuLz4WYTVuHr8ANLSy",
   "KT19bi9mhnXBytz2GLMuEcDvTU8c8MHs8Gm6"
  ],
  "__destination_map": {}
 }
}
2019-06-13 23:32:20,188 - MainThread - --------------------------------------------
2019-06-13 23:32:20,188 - MainThread - BAKING ADDRESS is tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1
2019-06-13 23:32:20,188 - MainThread - PAYMENT ADDRESS is tacccos
2019-06-13 23:32:20,188 - MainThread - --------------------------------------------
2019-06-13 23:32:26,839 - MainThread - Producer "producer" started
2019-06-13 23:32:26,843 - MainThread - If you want to send emails, populate email.ini file under current working directory.
2019-06-13 23:32:26,843 - MainThread - Consumer "consumer0" created
2019-06-13 23:32:26,844 - producer_retry_fail - Retry Fail thread "producer_retry_fail" started
2019-06-13 23:32:27,846 - MainThread - Application start completed
2019-06-13 23:32:27,846 - MainThread - --------------------------------------------
2019-06-13 23:32:34,181 - producer  - Checking for pending payments : checking 111 <= 117 - (5 + 1) - 0
2019-06-13 23:32:34,181 - producer  - Payment cycle is 111
2019-06-13 23:32:36,000 - producer  - Error at payment producer loop, will try again.
Traceback (most recent call last):
  File "/home/bakebaker/trd-v5/src/pay/payment_producer.py", line 204, in try_to_pay
    reward_model = self.reward_api.get_rewards_for_cycle_map(pymnt_cycle, verbose=self.verbose)
  File "/home/bakebaker/trd-v5/src/rpc/rpc_reward_api.py", line 47, in get_rewards_for_cycle_map
    "delegators"] = self.__get_delegators_and_delgators_balance(cycle)
  File "/home/bakebaker/trd-v5/src/rpc/rpc_reward_api.py", line 99, in __get_delegators_and_delgators_balance
    hash_snapshot_block = self.__get_snapshot_block_hash(cycle)
  File "/home/bakebaker/trd-v5/src/rpc/rpc_reward_api.py", line 141, in __get_snapshot_block_hash
    snapshots = parse_json_response(response)
  File "/home/bakebaker/trd-v5/src/util/rpc_utils.py", line 34, in parse_json_response
    raise Exception("Unknown client response format")
Exception: Unknown client response format
2019-06-13 23:32:52,204 - producer  - Checking for pending payments : checking 111 <= 117 - (5 + 1) - 0
2019-06-13 23:32:52,204 - producer  - Payment cycle is 111
2019-06-13 23:32:53,944 - producer  - Error at payment producer loop, will try again.
Traceback (most recent call last):
  File "/home/bakebaker/trd-v5/src/pay/payment_producer.py", line 204, in try_to_pay
    reward_model = self.reward_api.get_rewards_for_cycle_map(pymnt_cycle, verbose=self.verbose)
  File "/home/bakebaker/trd-v5/src/rpc/rpc_reward_api.py", line 47, in get_rewards_for_cycle_map
    "delegators"] = self.__get_delegators_and_delgators_balance(cycle)
  File "/home/bakebaker/trd-v5/src/rpc/rpc_reward_api.py", line 99, in __get_delegators_and_delgators_balance
    hash_snapshot_block = self.__get_snapshot_block_hash(cycle)
  File "/home/bakebaker/trd-v5/src/rpc/rpc_reward_api.py", line 141, in __get_snapshot_block_hash
    snapshots = parse_json_response(response)
  File "/home/bakebaker/trd-v5/src/util/rpc_utils.py", line 34, in parse_json_response
    raise Exception("Unknown client response format")
Exception: Unknown client response format
^C2019-06-13 23:32:56,555 - MainThread - Interrupted.
2019-06-13 23:32:56,555 - MainThread - --------------------------------------------------------
2019-06-13 23:32:56,555 - MainThread - Sensitive operations are in progress!
2019-06-13 23:32:56,556 - MainThread - Please wait while the application is being shut down!
2019-06-13 23:32:56,556 - MainThread - --------------------------------------------------------
2019-06-13 23:32:56,556 - MainThread - Lock file removed!
2019-06-13 23:33:03,955 - producer  - Producer returning ...
2019-06-13 23:33:03,956 - consumer0 - Exit signal received. Terminating...
2019-06-13 23:33:03,957 - consumer0 - Consumer returning ...
```

**Comment by habanoz** [comment]
We have an in issue with RPC. After Athens upgrade RPC layer has changed. Working on this issue. Please see #80 .

**Comment by habanoz** [comment]
Fix progress is in in fix_rpc branch.

**Comment by habanoz** [comment]
This is fixed.

**Comment by habanoz** [comment]
Closing due to inactivity.
