### ISSUE TITLE
Cannot make payments

### ISSUE THREAD

**Issue by Zoni16** [habanoz/tezos-reward-distributor#90]
**Describe the bug**
Cannot make payments, error is below

**To Reproduce**
Ran main.py (parameters don't matter)

python3 src/main.py -C 108 -M 3
 _____ ______ ______
|_   _|| ___ \|  _  \
  | |  | |_/ /| | | |
  | |  |    / | | | |
  | |  | |\ \ | |/ /
  \_/  \_| \_||___/

--------------------------------------------
Copyright Huseyin ABANOZ 2019
huseyinabanox@gmail.com
Please leave copyright information
--------------------------------------------
2019-06-16 13:41:38,473 - MainThread - Tezos Reward Distributor is Starting
2019-06-16 13:41:38,474 - MainThread - TRD version 5.6 is running in interactive mode.
2019-06-16 13:41:38,474 - MainThread - Arguments Configuration = {
 "network": "MAINNET",
 "reward_data_provider": "tzscan",
 "reports_base": "~/pymnt/reports",
 "config_dir": "~/pymnt/cfg",
 "node_addr": "127.0.0.1:8732",
 "dry_run": false,
 "dry_run_no_consumers": false,
 "executable_dirs": "~/,~/tezos",
 "docker": false,
 "verbose": false,
 "background_service": false,
 "do_not_publish_stats": false,
 "run_mode": 3,
 "release_override": 0,
 "payment_offset": 0,
 "initial_cycle": 108
}
2019-06-16 13:41:38,707 - MainThread - Loading baking configuration file /home/shehata_mina/pymnt/cfg/tz1UUgPwikRHW1mEyVZfGYy6QaxrY6Y7WaG5.yaml
2019-06-16 13:41:51,430 - MainThread - Baking Configuration {
 "master_dict": {},
 "cfg_dict": {
  "baking_address": "tz1UUgPwikRHW1mEyVZfGYy6QaxrY6Y7WaG5",
  "delegator_pays_xfer_fee": true,
  "founders_map": {},
  "min_delegation_amt": 0.0,
  "owners_map": {},
  "payment_address": "zonini",
  "rules_map": {
   "mindelegation": "TOB"
  },
  "service_fee": 10.0,
  "specials_map": {},
  "supporters_set": [],
  "__payment_address_type": null,
  "__payment_address_pkh": "tz1MN1BzEFM6UDvAD5CJSGkQb8zs5MDX35HD",
  "__payment_address_manager": "tz1MN1BzEFM6UDvAD5CJSGkQb8zs5MDX35HD",
  "__full_supporters_set": [],
  "__excluded_delegators_set_toe": [],
  "__excluded_delegators_set_tof": [],
  "__excluded_delegators_set_tob": [
   "mindelegation"
  ],
  "__destination_map": {}
 }
}
2019-06-16 13:41:51,431 - MainThread - --------------------------------------------
2019-06-16 13:41:51,431 - MainThread - BAKING ADDRESS is tz1UUgPwikRHW1mEyVZfGYy6QaxrY6Y7WaG5
2019-06-16 13:41:51,431 - MainThread - PAYMENT ADDRESS is zonini
2019-06-16 13:41:51,431 - MainThread - --------------------------------------------
2019-06-16 13:41:51,432 - MainThread - Producer "producer" started
2019-06-16 13:41:51,435 - MainThread - If you want to send emails, populate email.ini file under current working directory.
2019-06-16 13:41:51,435 - MainThread - Consumer "consumer0" created
2019-06-16 13:41:52,437 - MainThread - Application start completed
2019-06-16 13:41:52,437 - MainThread - --------------------------------------------
2019-06-16 13:41:57,326 - producer  - Checking for pending payments : checking 108 <= 117 - (5 + 1) - 0
2019-06-16 13:41:57,326 - producer  - Payment cycle is 108
2019-06-16 13:41:59,513 - producer  - Total rewards before processing is 1,070,711,795 mutez.
2019-06-16 13:41:59,515 - producer  - Total rewards after  processing is 1,070,711,795 mutez.
2019-06-16 13:41:59,523 - producer  - Calculation report is created at '/home/shehata_mina/pymnt/reports/tz1UUgPwikRHW1mEyVZfGYy6QaxrY6Y7WaG5/calculations/108.csv'
2019-06-16 13:41:59,523 - producer  - Reward creation is done for cycle 108, created 145 rewards.
2019-06-16 13:42:00,517 - consumer0 - Starting payments for cycle 108
2019-06-16 13:42:00,519 - consumer0 - 143 payment items to process
2019-06-16 13:42:00,519 - consumer0 - 37 payment items are not trivial, total of 9,367 mutez
2019-06-16 13:42:00,521 - consumer0 - Total trivial amount to pay is 666,426,379 mutez.
2019-06-16 13:42:00,521 - consumer0 - 106 trivial payments will be done in 1 batches
2019-06-16 13:42:01,713 - consumer0 - batch payment attempt 1/3 for current batch failed with error
Traceback (most recent call last):
  File "/home/shehata_mina/tezos-reward-distributor/src/pay/batch_payer.py", line 184, in pay_single_batch
    status, operation_hash = self.attempt_single_batch(payment_items, op_counter, verbose, dry_run=dry_run)
  File "/home/shehata_mina/tezos-reward-distributor/src/pay/batch_payer.py", line 245, in attempt_single_batch
    assert pymnt_amnt >= ZERO_THRESHOLD # zero check, zero amounts needs to be filtered out earlier
AssertionError
2019-06-16 13:42:09,534 - producer  - Run mode ONETIME satisfied. Terminating ...
2019-06-16 13:42:09,534 - producer  - Producer returning ...

**Comment by habanoz** [comment]
Until this is fixed, set min_delegation_amt to some value. Start from 10 and increase gradually until error is gone.

**Comment by habanoz** [comment]
This is fixed. Run a "git pull".

**Comment by Zoni16** [comment]
Thanks! Works for me
