### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by dmirgaleev** [habanoz/tezos-reward-distributor#91]
**Describe the bug**
Error while trying to process command "python3 src/main.py -N ALPHANET -M 3 -Dc -A 127.0.0.1:19332"

**To Reproduce**
Use main.py with options -N ALPHANET -A addr:port
**Expected behavior**
Error occurs.

**Screenshots**
python3 src/main.py -N ALPHANET -M 3 -Dc -A 127.0.0.1:19332
 _____ ______ ______
|_   _|| ___ \|  _  \
  | |  | |_/ /| | | |
  | |  |    / | | | |
  | |  | |\ \ | |/ /
  \_/  \_| \_||___/

--------------------------------------------
Copyright Huseyin ABANOZ 2019
huseyinabanox@gmail.com
Please leave copyright information
--------------------------------------------
2019-06-16 08:35:12,809 - MainThread - Tezos Reward Distributor is Starting
2019-06-16 08:35:12,812 - MainThread - TRD version 5.6 is running in interactive mode.
2019-06-16 08:35:12,812 - MainThread - Arguments Configuration = {
 "run_mode": 3,
 "node_addr": "127.0.0.1:19332",
 "dry_run_no_consumers": true,
 "initial_cycle": null,
 "release_override": 0,
 "background_service": false,
 "docker": false,
 "payment_offset": 0,
 "network": "ALPHANET",
 "reports_base": "~/pymnt/reports",
 "dry_run": false,
 "do_not_publish_stats": false,
 "config_dir": "~/pymnt/cfg",
 "reward_data_provider": "tzscan",
 "executable_dirs": "~/,~/tezos",
 "verbose": false
}
2019-06-16 08:35:13,167 - MainThread - Loading baking configuration file /home/a/pymnt/cfg/tz1PVAAVKbvASA79wBVVsgTVHvkEakupHJ9Y.yaml
Traceback (most recent call last):
  File "src/main.py", line 259, in <module>
    main(args)
  File "src/main.py", line 99, in main
    parser.validate()
  File "/home/a/tezos-reward-distributor/src/config/yaml_baking_conf_parser.py", line 27, in validate
    self.validate_payment_address(conf_obj)
  File "/home/a/tezos-reward-distributor/src/config/yaml_baking_conf_parser.py", line 119, in validate_payment_address
    addr_obj = self.wllt_clnt_mngr.get_addr_dict_by_pkh(pymnt_addr)
  File "/home/a/tezos-reward-distributor/src/cli/wallet_client_manager.py", line 66, in get_addr_dict_by_pkh
    self.generate_address_dict()
  File "/home/a/tezos-reward-distributor/src/cli/wallet_client_manager.py", line 82, in generate_address_dict
    self.contr_dict_by_alias = self.__list_known_contracts_by_alias()
  File "/home/a/tezos-reward-distributor/src/cli/wallet_client_manager.py", line 110, in __list_known_contracts_by_alias
    _, response = self.send_request(" list known contracts")
  File "/home/a/tezos-reward-distributor/src/cli/simple_client_manager.py", line 15, in send_request
    return self.cmd_manager.execute(whole_cmd, verbose_override, timeout=timeout)
  File "/home/a/tezos-reward-distributor/src/cli/cmd_manager.py", line 29, in execute
    output = check_output(cmd, shell=True, stderr=STDOUT, timeout=timeout, encoding='utf8')
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'encoding'

**Environment**
 - Source Code Build
 - Chain alphanet
 - python3 src/main.py -N ALPHANET -M 3 -Dc -A 127.0.0.1:19332

**Additional context**
I tried src/configure.py too and have the same error.

**Comment by habanoz** [comment]
This is a known issue.  Python 3.6 or later is needed.
Please see #85

**Comment by dmirgaleev** [comment]
Thanks!
