### ISSUE TITLE
 Counter already used - Error

### ISSUE THREAD

**Issue by marcoBros** [habanoz/tezos-reward-distributor#93]
## Environment
- Source code commit 10e7923
- Mainnet
- History mode full
- cmd : ```$ python3 src/main.py -E /../tezos-reward-distributor -M 3```

## Payment process is crashing this way :
```
2019-06-26 00:21:19,147 - MainThread - Tezos Reward Distributor is Starting
2019-06-26 00:21:19,149 - MainThread - TRD version 5.7 is running in interactive mode.
2019-06-26 00:21:19,149 - MainThread - Arguments Configuration = {
 "network": "MAINNET",
 "reward_data_provider": "tzscan",
 "reports_base": "~/pymnt/reports",
 "config_dir": "~/pymnt/cfg",
 "node_addr": "127.0.0.1:8732",
 "dry_run": false,
 "dry_run_no_consumers": false,
 "executable_dirs": "~/tezos/",
 "docker": false,
 "verbose": true,
 "background_service": false,
 "do_not_publish_stats": false,
 "run_mode": 3,
 "release_override": 0,
 "payment_offset": 0,
 "initial_cycle": null
}
2019-06-26 00:21:19,151 - MainThread - master configuration file not present.
2019-06-26 00:21:19,151 - MainThread - Tezos client path is ~/tezos/tezos-client
2019-06-26 00:21:19,151 - MainThread - Failed to get network configuration constants from a local node.
2019-06-26 00:21:19,363 - MainThread - Network configuration constants successfully loaded from a public node.
2019-06-26 00:21:19,363 - MainThread - Network config {'NB_FREEZE_CYCLE': 5, 'BLOCK_TIME_IN_SEC': 60, 'BLOCKS_PER_CYCLE': 4096, 'BLOCKS_PER_ROLL_SNAPSHOT': 256, 'NAME': 'MAINNET'}
2019-06-26 00:21:19,363 - MainThread - Loading baking configuration file /home/user/pymnt/cfg/tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V.yaml
2019-06-26 00:21:19,496 - MainThread - Available mirrors are: [1, 2, 3, 4, 5, 6]
2019-06-26 00:21:19,502 - MainThread - --> Verbose : Command is |~/tezos/tezos-client list known contracts|
2019-06-26 00:21:20,593 - MainThread - <-- Verbose : Answer is |wallet1: tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V|
2019-06-26 00:21:20,594 - MainThread - known contracts: {'wallet1': 'tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V'}
2019-06-26 00:21:20,594 - MainThread - Generating known address dictionary
2019-06-26 00:21:20,594 - MainThread - --> Verbose : Command is |~/tezos/tezos-client list known addresses|
2019-06-26 00:21:21,649 - MainThread - <-- Verbose : Answer is |wallet1: tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V (tcp sk known)|
2019-06-26 00:21:21,650 - MainThread - known addresses: {'tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V': {'alias': 'wallet1', 'sk': True}}
2019-06-26 00:21:21,650 - MainThread - Known address added: {'pkh': 'tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V', 'originated': False, 'alias': 'wallet1', 'sk': True, 'manager': 'tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V'}
2019-06-26 00:21:21,707 - MainThread - Baking Configuration {
 "master_dict": {},
 "cfg_dict": {
  "baking_address": "tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V",
  "delegator_pays_xfer_fee": false,
  "founders_map": {},
  "min_delegation_amt": 1.0,
  "owners_map": {},
  "payment_address": "wallet1",
  "rules_map": {
   "mindelegation": "TOB"
  },
  "service_fee": 10.0,
  "specials_map": {},
  "supporters_set": [],
  "__payment_address_type": null,
  "__payment_address_pkh": "tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V",
  "__payment_address_manager": "tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V",
  "__full_supporters_set": [],
  "__excluded_delegators_set_toe": [],
  "__excluded_delegators_set_tof": [],
  "__excluded_delegators_set_tob": [
   "mindelegation"
  ],
  "__destination_map": {}
 }
}
2019-06-26 00:21:21,709 - MainThread - --------------------------------------------
2019-06-26 00:21:21,709 - MainThread - BAKING ADDRESS is tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V
2019-06-26 00:21:21,709 - MainThread - PAYMENT ADDRESS is wallet1
2019-06-26 00:21:21,709 - MainThread - --------------------------------------------
2019-06-26 00:21:21,710 - MainThread - initial_cycle set to 0
2019-06-26 00:21:21,711 - MainThread - Producer "producer" started
2019-06-26 00:21:21,713 - MainThread - If you want to send emails, populate email.ini file under current working directory.
2019-06-26 00:21:21,713 - MainThread - Consumer "consumer0" created
2019-06-26 00:21:21,774 - producer  - Payment cycle is set to 115
2019-06-26 00:21:22,715 - MainThread - Application start completed
2019-06-26 00:21:22,715 - MainThread - --------------------------------------------
2019-06-26 00:21:26,780 - producer  - Requesting https://api5.tzscan.io/v2/head
2019-06-26 00:21:26,825 - producer  - Response from tzscan is: {'hash': 'BKnQfVv8Zzbp7uwoiF8gbHPXcRD5L6RN3RQGyafYFyJtRLySKqv', 'predecessor_hash': 'BLL6KYXJGNtcwZ5WzvCicmD9PkravZwuLXHDv5DoGafoCHxpVSM', 'fitness': '00 0000000000edb2fa', 'timestamp': '2019-06-26T00:20:38Z', 'validation_pass': 4, 'operations': [[]], 'protocol': {'name': 'Pt24m4xiPbLDhVgVfABUjirbmda3yohdN82Sp9FeuAXJ4eV9otd', 'hash': 'Pt24m4xiPbLDhVgVfABUjirbmda3yohdN82Sp9FeuAXJ4eV9otd'}, 'test_protocol': {'name': 'Pt24m4xiPbLDhVgVfABUjirbmda3yohdN82Sp9FeuAXJ4eV9otd', 'hash': 'Pt24m4xiPbLDhVgVfABUjirbmda3yohdN82Sp9FeuAXJ4eV9otd'}, 'network': 'NetXdQprcVkpaWU', 'test_network': 'Not running', 'test_network_expiration': 'Not running', 'baker': {'tz': 'tz3RDC3Jdn4j15J7bBHZd29EUee9gVB1CxD9', 'alias': 'Foundation Baker 1'}, 'nb_operations': 25, 'priority': 0, 'level': 495852, 'commited_nonce_hash': '', 'pow_nonce': '000000032d1d6072', 'proto': 4, 'data': '--', 'signature': 'sigupfNqXLykdgR3u6YmsLw71qRTWsozgFdQ3ujmbn5YNhgK5aDQaiGo3YtXGVSzTBAHZimZdKa8yi1T85Uekfmo1emCxnCa', 'volume': '2456000000', 'fees': 51420, 'distance_level': 0}
2019-06-26 00:21:26,826 - producer  - Checking for pending payments : payment_cycle <= current_cycle - (self.nw_config['NB_FREEZE_CYCLE'] + 1) - self.release_override
2019-06-26 00:21:26,826 - producer  - Checking for pending payments : checking 115 <= 121 - (5 + 1) - 0
2019-06-26 00:21:26,827 - producer  - Payment cycle is 115
2019-06-26 00:21:27,450 - producer  - Total rewards before processing is 331,001,500 mutez.
2019-06-26 00:21:27,452 - producer  - Total rewards after  processing is 331,001,497 mutez.
2019-06-26 00:21:27,453 - producer  - Total amount to pay is 331,001,500 mutez
2019-06-26 00:21:27,453 - producer  - Difference between total rewards and total payment amount is 3 mutez. This is due to floating point arithmetic. (max allowed diff is 10)
2019-06-26 00:21:27,453 - producer  - Creating calculation report (/home/user/pymnt/reports/tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V/calculations/115.csv)
2019-06-26 00:21:27,454 - producer  - Reward created for address KT1A9qf3MJTCTK7ZwT7ToAjbjfyeLMonDdBc type D balance  101568.51 ratio 0.14275643 fee_ratio 0.015862 amount    47.25 fee_amount 5.25 fee_rate 0.10 payable True skipped False atphase 0 desc 
2019-06-26 00:21:27,454 - producer  - Reward created for address KT1eLgt6zc9PAoJSxFajjCXSc2GvFsvqDG5r type D balance  100969.76 ratio 0.14191488 fee_ratio 0.015768 amount    46.97 fee_amount 5.22 fee_rate 0.10 payable True skipped False atphase 0 desc

... 

2019-06-26 00:21:27,465 - producer  - Calculation report is created at '/home/user/pymnt/reports/tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V/calculations/115.csv'
2019-06-26 00:21:27,466 - producer  - Reward creation is done for cycle 115, created 43 rewards.
2019-06-26 00:21:28,455 - consumer0 - Starting payments for cycle 115
2019-06-26 00:21:28,457 - consumer0 - Transfer fee is paid by Delegate
2019-06-26 00:21:28,457 - consumer0 - Payment address is tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V
2019-06-26 00:21:28,457 - consumer0 - Signing address is tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V, manager alias is wallet1
2019-06-26 00:21:28,458 - consumer0 - 38 payment items to process
2019-06-26 00:21:28,458 - consumer0 - Total trivial amount to pay is 259,773,819 mutez.
2019-06-26 00:21:28,458 - consumer0 - 38 trivial payments will be done in 1 batches
2019-06-26 00:21:28,459 - consumer0 - Payment of batch 1 started
2019-06-26 00:21:28,459 - consumer0 - --> Verbose : Command is |~/tezos/tezos-client rpc get http://127.0.0.1:8732/chains/main/blocks/head/context/contracts/tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V/counter|
2019-06-26 00:21:29,387 - consumer0 - <-- Verbose : Answer is |"215690"|
2019-06-26 00:21:30,474 - consumer0 - head: branch BMam8MC2sSN8SUEZtiaqf6okfmPd5aDdZAJ3BsAxz2yLeJXt999 counter 215690 protocol Pt24m4xiPbLDhVgVfABUjirbmda3yohdN82Sp9FeuAXJ4eV9otd
2019-06-26 00:21:30,477 - consumer0 - Payment content: {"kind":"transaction","source":"tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V","destination":"KT1A9qf3MJTCTK7ZwT7ToAjbjfyeLMonDdBc","fee":"1480","counter":"215691","gas_limit": "10200", "storage_limit": "0","amount":"47252591"}
2019-06-26 00:21:30,478 - consumer0 - Payment content: {"kind":"transaction","source":"tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V","destination":"KT1eLgt6zc9PAoJSxFajjCXSc2GvFsvqDG5r","fee":"1480","counter":"215692","gas_limit": "10200", "storage_limit": "0","amount":"46974039"}

...

2019-06-26 00:21:30,495 - consumer0 - Running 38 operations
2019-06-26 00:21:30,496 - consumer0 - --> Verbose : Command is |~/tezos/tezos-client rpc post http://127.0.0.1:8732/chains/main/blocks/head/helpers/scripts/run_operation with '{"branch": "BMam8MC2sSN8SUEZtiaqf6okfmPd5aDdZAJ3BsAxz2yLeJXt999","contents":[{"kind":"transaction","source":"tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V","destination":"KT1A9qf3MJTCTK7ZwT7ToAjbjfyeLMonDdBc","fee":"1480","counter":"215691","gas_limit": "10200", "storage_limit": "0","amount":"47252591"},{"kind":"transaction","source":"tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V","destination":"KT1eLgt6zc9PAoJSxFajjCXSc2GvFsvqDG5r","fee":"1480","counter":"215692","gas_limit": "10200", "storage_limit": "0","amount":"46974039"}

...

], "signature":"edsigtXomBKi5CTRf5cjATJWfQDTuqHhuA8b2d8NarZjz8TRf65WkpQmo423BtomS8QSyaRvhfYNHqSUGrn4SdbYRcGwQrUGjzE"}'|
2019-06-26 00:21:31,566 - consumer0 - <-- Verbose : Answer is |{ "contents":
    [ { "kind": "transaction",
        "source": "tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V", "fee": "1480",
        "counter": "215691", "gas_limit": "10200", "storage_limit": "0",
        "amount": "47252591",
        "destination": "KT1A9qf3MJTCTK7ZwT7ToAjbjfyeLMonDdBc",
        "metadata":
          { "balance_updates":
              [ { "kind": "contract",
                  "contract": "tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V",
                  "change": "-1480" },
                { "kind": "freezer", "category": "fees",
                  "delegate": "tz1Ke2h7sDdakHJQh8WX4Z372du1KChsksyU",
                  "cycle": 121, "change": "1480" } ],
            "operation_result":
              { "status": "applied",
                "balance_updates":
                  [ { "kind": "contract",
                      "contract": "tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V",
                      "change": "-47252591" },
                    { "kind": "contract",
                      "contract": "KT1A9qf3MJTCTK7ZwT7ToAjbjfyeLMonDdBc",
                      "change": "47252591" } ], "consumed_gas": "10200" } } },
      { "kind": "transaction",
        "source": "tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V", "fee": "1480",
        "counter": "215692", "gas_limit": "10200", "storage_limit": "0",
        "amount": "46974039",
        "destination": "KT1eLgt6zc9PAoJSxFajjCXSc2GvFsvqDG5r",
        "metadata":
          { "balance_updates":
              [ { "kind": "contract",
                  "contract": "tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V",
                  "change": "-1480" },
                { "kind": "freezer", "category": "fees",
                  "delegate": "tz1Ke2h7sDdakHJQh8WX4Z372du1KChsksyU",
                  "cycle": 121, "change": "1480" } ],
            "operation_result":
              { "status": "applied",
                "balance_updates":
                  [ { "kind": "contract",
                      "contract": "tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V",
                      "change": "-46974039" },
                    { "kind": "contract",
                      "contract": "KT1eLgt6zc9PAoJSxFajjCXSc2GvFsvqDG5r",
                      "change": "46974039" } ], "consumed_gas": "10200" } } },

...      

 ] }|
2019-06-26 00:21:31,572 - consumer0 - Forging 38 operations
2019-06-26 00:21:31,572 - consumer0 - --> Verbose : Command is |~/tezos/tezos-client rpc post http://127.0.0.1:8732/chains/main/blocks/head/helpers/forge/operations with '{"branch": "BMam8MC2sSN8SUEZtiaqf6okfmPd5aDdZAJ3BsAxz2yLeJXt999","contents":[{"kind":"transaction","source":"tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V","destination":"KT1A9qf3MJTCTK7ZwT7ToAjbjfyeLMonDdBc","fee":"1480","counter":"215691","gas_limit": "10200", "storage_limit": "0","amount":"47252591"},{"kind":"transaction","source":"tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V","destination":"KT1eLgt6zc9PAoJSxFajjCXSc2GvFsvqDG5r","fee":"1480","counter":"215692","gas_limit": "10200", "storage_limit": "0","amount":"46974039"}

...

]}'|
2019-06-26 00:21:32,459 - consumer0 - <-- Verbose : Answer is |"f650b2c22d2a29e9932955862e8e297..."|
2019-06-26 00:21:32,459 - consumer0 - ->will parse json response_str is '"f650b2c22d2a29e9932955862e8e297..."'
2019-06-26 00:21:32,459 - consumer0 - <-parsed json response_str is '"f650b2c22d2a29e9932955862e8e297..."'
2019-06-26 00:21:32,459 - consumer0 - --> Verbose : Command is |~/tezos/tezos-client sign bytes 0x03f650b2c22d2a29e9932955862e8e297... for wallet1|
2019-06-26 00:21:34,591 - consumer0 - <-- Verbose : Answer is |Signature: sigkavmN3Kg7wLEteMMVJ6cHGBL5HnwHi391Xfwrfg2UQLPjWw9bHK1edMVHCSFiDAL1FoDmwvEktJc4T3PFWHEs7xWoQK91|
2019-06-26 00:21:34,591 - consumer0 - Preapplying the operations
2019-06-26 00:21:34,591 - consumer0 - --> Verbose : Command is |~/tezos/tezos-client rpc post http://127.0.0.1:8732/chains/main/blocks/head/helpers/preapply/operations with '[{"protocol":"Pt24m4xiPbLDhVgVfABUjirbmda3yohdN82Sp9FeuAXJ4eV9otd","branch":"BMam8MC2sSN8SUEZtiaqf6okfmPd5aDdZAJ3BsAxz2yLeJXt999","contents":[{"kind":"transaction","source":"tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V","destination":"KT1A9qf3MJTCTK7ZwT7ToAjbjfyeLMonDdBc","fee":"1480","counter":"215691","gas_limit": "10200", "storage_limit": "0","amount":"47252591"},{"kind":"transaction","source":"tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V","destination":"KT1eLgt6zc9PAoJSxFajjCXSc2GvFsvqDG5r","fee":"1480","counter":"215692","gas_limit": "10200", "storage_limit": "0","amount":"46974039"}

...

],"signature":"sigkavmN3Kg7wLEteMMVJ6cHGBL5HnwHi391Xfwrfg2UQLPjWw9bHK1edMVHCSFiDAL1FoDmwvEktJc4T3PFWHEs7xWoQK91"}]'|
2019-06-26 00:21:35,589 - consumer0 - <-- Verbose : Answer is |[ { "contents":
      [ { "kind": "transaction",
          "source": "tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V", "fee": "1480",
          "counter": "215691", "gas_limit": "10200", "storage_limit": "0",
          "amount": "47252591",
          "destination": "KT1A9qf3MJTCTK7ZwT7ToAjbjfyeLMonDdBc",
          "metadata":
            { "balance_updates":
                [ { "kind": "contract",
                    "contract": "tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V",
                    "change": "-1480" },
                  { "kind": "freezer", "category": "fees",
                    "delegate": "tz1Ke2h7sDdakHJQh8WX4Z372du1KChsksyU",
                    "cycle": 121, "change": "1480" } ],
              "operation_result":
                { "status": "applied",
                  "balance_updates":
                    [ { "kind": "contract",
                        "contract": "tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V",
                        "change": "-47252591" },
                      { "kind": "contract",
                        "contract": "KT1A9qf3MJTCTK7ZwT7ToAjbjfyeLMonDdBc",
                        "change": "47252591" } ], "consumed_gas": "10200" } } },
        { "kind": "transaction",
          "source": "tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V", "fee": "1480",
          "counter": "215692", "gas_limit": "10200", "storage_limit": "0",
          "amount": "46974039",
          "destination": "KT1eLgt6zc9PAoJSxFajjCXSc2GvFsvqDG5r",
          "metadata":
            { "balance_updates":
                [ { "kind": "contract",
                    "contract": "tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V",
                    "change": "-1480" },
                  { "kind": "freezer", "category": "fees",
                    "delegate": "tz1Ke2h7sDdakHJQh8WX4Z372du1KChsksyU",
                    "cycle": 121, "change": "1480" } ],
              "operation_result":
                { "status": "applied",
                  "balance_updates":
                    [ { "kind": "contract",
                        "contract": "tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V",
                        "change": "-46974039" },
                      { "kind": "contract",
                        "contract": "KT1eLgt6zc9PAoJSxFajjCXSc2GvFsvqDG5r",
                        "change": "46974039" } ], "consumed_gas": "10200" } } },

...        

 ],
    "signature":
      "sigkavmN3Kg7wLEteMMVJ6cHGBL5HnwHi391Xfwrfg2UQLPjWw9bHK1edMVHCSFiDAL1FoDmwvEktJc4T3PFWHEs7xWoQK91" } ]|
2019-06-26 00:21:35,594 - consumer0 - Injecting 38 operations
2019-06-26 00:21:35,594 - consumer0 - --> Verbose : Command is |~/tezos/tezos-client rpc post http://127.0.0.1:8732/injection/operation with '"f650b2c22d2a29e9932955862e8e297..."'|
2019-06-26 00:21:36,610 - consumer0 - <-- Verbose : Answer is |Command failed : Unregistred error:
                   { "kind": "generic",
                     "error":
                       "Error while applying operation ooTANshzJQ2XpgN2az35T6uUATY8jMUD6KWn6xLTnCnpxhXojha:\nbranch refused (Error:\n                  Counter 215691 already used for contract tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V (expected 215729)\n)" }|
2019-06-26 00:21:36,610 - consumer0 - Operation hash is {'kind': 'generic', 'error': 'Error while applying operation ooTANshzJQ2XpgN2az35T6uUATY8jMUD6KWn6xLTnCnpxhXojha:\nbranch refused (Error:\n                  Counter 215691 already used for contract tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V (expected 215729)\n)'}
2019-06-26 00:21:36,611 - consumer0 - Waiting for operation {'kind': 'generic', 'error': 'Error while applying operation ooTANshzJQ2XpgN2az35T6uUATY8jMUD6KWn6xLTnCnpxhXojha:\nbranch refused (Error:\n                  Counter 215691 already used for contract tz1MTLrFwjGKkM0RG1KSf5wPJERxPcm2wU6V (expected 215729)\n)'} to be included. Please be patient until the block has 1 confirmation(s)
2019-06-26 00:21:36,611 - consumer0 - batch payment attempt 1/3 for current batch failed with error
Traceback (most recent call last):
  File "/home/user/tezos-reward-distributor/src/pay/batch_payer.py", line 184, in pay_single_batch
    status, operation_hash = self.attempt_single_batch(payment_items, op_counter, verbose, dry_run=dry_run)
  File "/home/user/tezos-reward-distributor/src/pay/batch_payer.py", line 356, in attempt_single_batch
    cmd = self.comm_wait.replace("%OPERATION%", operation_hash)
TypeError: replace() argument 2 must be str, not dict
2019-06-26 00:21:36,613 - consumer0 - payment attempt 1/3 failed
2019-06-26 00:21:36,613 - consumer0 - Wait for 57 seconds before trying again
2019-06-26 00:21:37,476 - producer  - Run mode ONETIME satisfied. Terminating ...
2019-06-26 00:21:37,477 - producer  - Producer returning ...
2019-06-26 00:21:41,116 - MainThread - Interrupted.
2019-06-26 00:21:41,117 - MainThread - --------------------------------------------------------
2019-06-26 00:21:41,117 - MainThread - Sensitive operations are in progress!
2019-06-26 00:21:41,118 - MainThread - Please wait while the application is being shut down!
2019-06-26 00:21:41,118 - MainThread - --------------------------------------------------------
2019-06-26 00:21:41,118 - MainThread - Lock file removed!

```

**Comment by habanoz** [comment]
How often do you get this error?

Each batch is tried 3 times in a row, I can see only the first attempts here, what happened in following attempts?

Is it possible another wallet operation is executed in the mean time?

**Comment by marcoBros** [comment]
I executed the script payment in dry mode first. Next after I executed script payment in normal mode and I got this error.

The difference between the counter used and the counter proposed in error message is exactly the number of transaction signed during dry mode.

No other wallet operation is executed.

**Comment by habanoz** [comment]
This sounds weird. From logs it is visible that counter is used correctly. However, node rejects it. We need more information to resolve this.

**Comment by habanoz** [comment]
Closing due to inactivity.
