### ISSUE TITLE
lost_rewards_denounciation - Error

### ISSUE THREAD

**Issue by dansan566** [habanoz/tezos-reward-distributor#95]
**Describe the bug**
I use TRD frequently. Last payments for cycle 129 were made three days ago without any issue. I'm getting this error for payment cycle 130:
```
  File "/tezos-reward-distributor/src/pay/payment_producer.py", line 204, in try_to_pay
    reward_model = self.reward_api.get_rewards_for_cycle_map(pymnt_cycle)
  File "/tezos-reward-distributor/src/tzscan/tzscan_reward_api.py", line 27, in get_rewards_for_cycle_map
    lost_rewards_denounciation = int(root["lost_rewards_denounciation"])
KeyError: 'lost_rewards_denounciation'
```
**Expected behavior**
Payout for Cycle 130 with reports.

**Environment**
 - TRD version 5.11 is running in interactive mode.
 - mainnet
 - python3 src/main.py -C 130 -M 3
- python3 src/main.py -C 130 -D -M 3

**Comment by Zoni16** [comment]
Same issue here, before cycle 130 was just fine

**Comment by dansan566** [comment]
Possible change of API from tzscan?

**Comment by jdsika** [comment]
[APIs](https://tzscan.io/api#operation/312)
> lost_rewards_denounciation_endorsement required | integer <int64>
> lost_rewards_denounciation_baking required | integer <int64>

Did they split the call into "baking" and "endorsement"?

**Comment by jdsika** [comment]
@Zoni16 try my PR and provide feedback please

**Comment by Zoni16** [comment]
@jdsika Thank you, works just fine

**Comment by amani1104** [comment]
@jdsika Does not work for me:

```
File "src/main.py", line 11, in <module>
    from api.provider_factory import ProviderFactory
  File "/home/tezos/tezos-reward-distributor/src/api/provider_factory.py", line 1, in <module>
    from rpc.lrpc_reward_api import LRpcRewardApiImpl
  File "/home/tezos/tezos-reward-distributor/src/rpc/lrpc_reward_api.py", line 10, in <module>
    from tzscan.tzscan_reward_api import TzScanRewardApiImpl
  File "/home/tezos/tezos-reward-distributor/src/tzscan/tzscan_reward_api.py", line 28
    + int(root["lost_rewards_denounciation_endorsement"])
    ^
IndentationError: unexpected indent
```

**Comment by jdsika** [comment]
@amani1104 can you try again. I removed the spaces.

**Comment by amani1104** [comment]
@jdsika Works like a charm now. Thank you!

**Comment by amani1104** [comment]
I guess this bug is related to the double endorsement events last cycle?

**Comment by labeoVlad** [comment]
Thank you jdska
I've used your code described here https://github.com/vDL-Digital-Ventures/tezos-reward-distributor/commit/a0634dce4917d7315d38493127404d5540f21c71
and it worked nicely

**Comment by SemElVik** [comment]
https://github.com/vDL-Digital-Ventures/tezos-reward-distributor/commit/a0634dce4917d7315d38493127404d5540f21c71 
this does not work

**Comment by goodpen** [comment]
same

**Comment by goodpen** [comment]
what i need to do guys? pls help

this does not work

Traceback (most recent call last):
  File "src/main.py", line 11, in <module>
    from api.provider_factory import ProviderFactory
  File "/home/alex/tezos-reward-distributor/src/api/provider_factory.py", line 1, in <module>
    from rpc.lrpc_reward_api import LRpcRewardApiImpl
  File "/home/alex/tezos-reward-distributor/src/rpc/lrpc_reward_api.py", line 10, in <module>
    from tzscan.tzscan_reward_api import TzScanRewardApiImpl
  File "/home/alex/tezos-reward-distributor/src/tzscan/tzscan_reward_api.py", line 28
    +
    ^
IndentationError: unexpected indent

**Comment by habanoz** [comment]
Thanks @jdsika . Issue is resolved.

**Comment by Michshelle** [comment]
Hello everyone,

I keep seeing this error, even I'm using the latest version of the TRD.  I'm running on MacOs.
As it's my first time use auto-payment system, I can be my bad.  Only I cannot figure it out.

Thank you very much for the help!

**Part of the log** (FYI, I removed the tz1 address)
`2019-08-13 01:25:56,973 - MainThread - Baking Configuration {
 "master_dict": {},
 "cfg_dict": {
  "version": 1.0,
  "baking_address": "tz1XXX",
  "payment_address": "tz1XXX",
  "service_fee": 5,
  "founders_map": {},
  "owners_map": {},
  "specials_map": {},
  "supporters_set": [],
  "min_delegation_amt": 500,
  "excluded_delegators_set": {},
  "delegator_pays_xfer_fee": true,
  "rules_map": {
   "mindelegation": "TOB"
  },
  "__payment_address_type": "TZ",
  "__payment_address_pkh": "tz1XXX",
  "__payment_address_manager": "tz1XXX",
  "__full_supporters_set": [],
  "__excluded_delegators_set_toe": [],
  "__excluded_delegators_set_tof": [],
  "__excluded_delegators_set_tob": [
   "mindelegation"
  ],
  "__destination_map": {}
 }
}
2019-08-13 01:25:56,973 - MainThread - --------------------------------------------
2019-08-13 01:25:56,974 - MainThread - BAKING ADDRESS is tz1XXX
2019-08-13 01:25:56,974 - MainThread - PAYMENT ADDRESS is tz1XXX
2019-08-13 01:25:56,974 - MainThread - --------------------------------------------
2019-08-13 01:25:56,974 - MainThread - initial_cycle set to 0
2019-08-13 01:25:56,975 - MainThread - Producer "producer" started
2019-08-13 01:25:56,977 - MainThread - If you want to send emails, populate email.ini file under current working directory.
2019-08-13 01:25:56,978 - MainThread - Consumer "consumer0" created
2019-08-13 01:25:57,978 - MainThread - Application start completed
2019-08-13 01:25:57,979 - MainThread - --------------------------------------------
2019-08-13 01:26:05,547 - producer  - Checking for pending payments : checking 131 <= 137 - (5 + 1) - 0
2019-08-13 01:26:05,547 - producer  - Payment cycle is 131
2019-08-13 01:26:06,154 - producer  - Error at payment producer loop, will try again.
Traceback (most recent call last):
  File "/Users/wich/tezos-reward-distributor/src/pay/payment_producer.py", line 204, in try_to_pay
    reward_model = self.reward_api.get_rewards_for_cycle_map(pymnt_cycle)
  File "/Users/wich/tezos-reward-distributor/src/tzscan/tzscan_reward_api.py", line 27, in get_rewards_for_cycle_map
    lost_rewards_denounciation = int(root["lost_rewards_denounciation_baking"])+int(root["lost_rewards_denounciation_endorsement"])
KeyError: 'lost_rewards_denounciation_baking'
2019-08-13 01:26:22,104 - producer  - Checking for pending payments : checking 131 <= 137 - (5 + 1) - 0
2019-08-13 01:26:22,105 - producer  - Payment cycle is 131
2019-08-13 01:26:22,568 - producer  - Error at payment producer loop, will try again.
Traceback (most recent call last):
  File "/Users/wich/tezos-reward-distributor/src/pay/payment_producer.py", line 204, in try_to_pay
    reward_model = self.reward_api.get_rewards_for_cycle_map(pymnt_cycle)
  File "/Users/wich/tezos-reward-distributor/src/tzscan/tzscan_reward_api.py", line 27, in get_rewards_for_cycle_map
    lost_rewards_denounciation = int(root["lost_rewards_denounciation_baking"])+int(root["lost_rewards_denounciation_endorsement"])
KeyError: 'lost_rewards_denounciation_baking'
`

**Comment by jdsika** [comment]
@SemElVik and @goodpen please use the current master because there was a bad space in the code which has been removed.

@Michshelle I am not sure about your error. I think I have to hand it to @habanoz for investigation.

**Comment by Michshelle** [comment]
FYI, I'm using a ledger nano S, but it seems not the cause to the problem..
